In [1]:
'''
Related papers:

1.https://openaccess.thecvf.com/content_CVPR_2020/papers/Liu_ABCNet_Real-Time_Scene_Text_Spotting_With_Adaptive_Bezier-Curve_Network_CVPR_2020_paper.pdf
2.https://arxiv.org/abs/1901.03781
3.Line Segment Detection Using Transformers without Edge [https://arxiv.org/pdf/2101.01909v1.pdf]

Dataset:
(1242 images / 500x500 / ../DATA)
https://openaccess.thecvf.com/content/ACCV2020/html/Abdelfattah_TTPLA_An_Aerial-Image_Dataset_for_Detection_and_Segmentation_of_Transmission_ACCV_2020_paper.html
'''

'\nRelated papers:\n\n1.https://openaccess.thecvf.com/content_CVPR_2020/papers/Liu_ABCNet_Real-Time_Scene_Text_Spotting_With_Adaptive_Bezier-Curve_Network_CVPR_2020_paper.pdf\n2.https://arxiv.org/abs/1901.03781\n3.Line Segment Detection Using Transformers without Edge [https://arxiv.org/pdf/2101.01909v1.pdf]\n\nDataset:\n(1242 images / 500x500 / ../DATA)\nhttps://openaccess.thecvf.com/content/ACCV2020/html/Abdelfattah_TTPLA_An_Aerial-Image_Dataset_for_Detection_and_Segmentation_of_Transmission_ACCV_2020_paper.html\n'

In [2]:
#imports

import os
#restrict gpu usage
os.environ["CUDA_VISIBLE_DEVICES"]="3"

from PIL import Image
import cv2
import bezier
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

# setting theme
px = 1/plt.rcParams['figure.dpi']
#sns.set(style=None, rc={'figure.figsize':(256*px, 256*px)})

# generate random floating point values
from numpy.random import seed, rand, randint
from random import gauss

In [11]:
%matplotlib agg

#[pixeldata, vectordata, length, label]
raw = []

def create_dataset():
    for _ in range(500):
        
        cpgen = rand(2, 2)
        sizer = randint(2,10,2)
        #plt.rcParams["figure.figsize"] = (sizer)

        nodes1 = np.asfortranarray(cpgen)
        curve1 = bezier.Curve(nodes1, degree=1)
        ax = curve1.plot(num_pts=256)
        ax.set(xlim=(0, 1), ylim=(0, 1))
        ax.set_axis_off()

        fig2 = plt.figure()
        fig2.axes.append(ax)
        
        #plt.show()
        path = "./custom/li_{}.jpg".format(_)
        
        #save image
        ax.figure.savefig(path, dpi=None)
        
        size = fig2.get_size_inches()*fig2.dpi # size in pixels
        w, h = size
        #print(size)
        #open image
        #im = Image.open(path).convert("L")
        #width, height = im.size
        #pdata = list(im.getdata())
        #ndata = np.array(pdata)
        #ndata = np.array(pdata).reshape((width, height, 3))
        
        # Retrieve a view on the renderer buffer
        #canvas.draw()
        #buf = canvas.buffer_rgba()
        # convert to a NumPy array
        #X = np.asarray(buf)
        #print("X is", X)
        #plt.imshow(X)
        #print("ax", ax)
        #SG_imagedata(curve1)
        #print("ax.figure", type(ax.figure))
        cap_data = np.array([nodes1, w, h, curve1.length], dtype="object")
        raw.append(cap_data)
        
        plt.close('all')
    
#create_dataset()
'''
ax = curve1.plot(num_pts=256)
ax.axis("off")
ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)
#ax.figure.savefig('out.png', bbox_inches='tight', pad_inches=0)
'''


'\nax = curve1.plot(num_pts=256)\nax.axis("off")\nax.get_xaxis().set_visible(False)\nax.get_yaxis().set_visible(False)\n#ax.figure.savefig(\'out.png\', bbox_inches=\'tight\', pad_inches=0)\n'

In [15]:
def ind_return(filename):
    idx_s = filename.split("_")
    idx_n = int(idx_s[1])
    
    # find idx_n in raw[]
    boxes, w, h, length = raw[idx_n]
    print(boxes, w, h, length)
    return boxes, w, h, length
    
ind_return("li_2")

[[0.5502912  0.67054799]
 [0.12242337 0.10892456]] 640.0 480.0 0.1210120415324922
[[0.73924551 0.99989404]
 [0.27386608 0.4416454 ]] 640.0 480.0 0.30997992781016526
[[0.37531773 0.28453239]
 [0.13970353 0.35987397]] 640.0 480.0 0.23815330885505137


(array([[0.37531773, 0.28453239],
        [0.13970353, 0.35987397]]),
 640.0,
 480.0,
 0.23815330885505137)