# Generate images

In [18]:
#imports
import os
import glob
#restrict gpu usage
os.environ["CUDA_VISIBLE_DEVICES"]="3"

from PIL import Image
import cv2
import bezier
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from matplotlib.patches import Rectangle

# setting theme
#px = 1/plt.rcParams['figure.dpi']
#sns.set(style=None, rc={'figure.figsize':(256*px, 256*px)})

# generate random floating point values
from numpy.random import seed, rand, randint
from random import gauss

# clear folders and files

In [19]:
for i in (['workspace/mobile/images/multi_lines/imgs/*', 
          'workspace/mobile/images/multi_lines/train/*', 
          'workspace/mobile/images/multi_lines/test/*']):
    files = glob.glob(i)
    for f in files:
        os.remove(f)
    
os.remove('workspace/mobile/images/multi_lines/train.csv')
os.remove('workspace/mobile/images/multi_lines/test.csv')

# Generate XML

In [20]:
# for xml generation

import xml.etree.cElementTree as ET

def xmlgen2(foln, fn, path, a_path, width, height, random_nodes, length):

    root = ET.Element("annotation")
    folder = ET.SubElement(root, "folder").text = foln
    filename = ET.SubElement(root, "filename").text = fn+'.png'
    path = ET.SubElement(root, "path").text = path
    source = ET.SubElement(root, "source") 
    
    ET.SubElement(source, "database").text = "unknown"
    
    size = ET.SubElement(root, "size")

    ET.SubElement(size, "width").text = width
    ET.SubElement(size, "height").text = height
    
    segmented = ET.SubElement(root, "segmented").text = "0"
    _object = ET.SubElement(root, "_object")
    
    ET.SubElement(_object, "name").text = fn
    ET.SubElement(_object, "pose").text = "Unspecified"
    
    lengths = ET.SubElement(_object, "lengths")
    
    for i,j in enumerate(length):
        ET.SubElement(lengths, "l_{}".format(i)).text = str(j)
        
    ET.SubElement(_object, "truncated").text = "0"
    ET.SubElement(_object, "difficult").text = "0"
    
    bndboxs = ET.SubElement(_object, "bndboxs")
    
    for i,j in enumerate(random_nodes):
        x_0, x_1, x_2, y_0, y_1, y_2 = j
        
        hook = ET.SubElement(bndboxs, "b_{}".format(i))
        ET.SubElement(hook, "x_0").text = str(x_0)
        ET.SubElement(hook, "x_1").text = str(x_1)
        ET.SubElement(hook, "x_2").text = str(x_2)
        ET.SubElement(hook, "y_0").text = str(y_0)
        ET.SubElement(hook, "y_1").text = str(y_1)
        ET.SubElement(hook, "y_2").text = str(y_2)
    
    tree = ET.ElementTree(root)
    tree.write(a_path)

# get all raw images 
def xmlmaker2(arr):
        fn, random_nodes, length = arr
        '''
        x, y = random_nodes
        xmin = str(x[0])
        ymin = str(x[1])
        xmax = str(y[0])
        ymax = str(y[1])
        '''
        width = str(image_width)
        height = str(image_height)

        foln = "./workspace/mobile/images/multi_lines/"
        fn = fn
        path = "{}/imgs/{}.png".format(foln, fn)
        a_path = "{}/imgs/{}.xml".format(foln, fn)
        xmlgen2(foln, fn, path, a_path, width, height, random_nodes, length)
        
#xmlmaker()

# line maker

In [23]:
image_height = image_width = 400
# for 600x600, inches = 8.334,8.334
# for 144x144, inches = 2,2

def multi_line_datasetGen(_, randLines):
        fig = plt.gcf()
        fig.set_size_inches(5.56,5.56)
        ax = plt.subplot()

        ax.set_axis_off()

        plt.axis([0, image_height, 0, image_width])
        plt.tight_layout(pad=0)

        #randLines = np.random.randint(iStart, iStop)
        
        random_nodes = []
        curveLength = []
    
        
        for i in range(randLines):
            r_nodes = np.random.uniform(0,image_width,[2,3])
            
            print(r_nodes)
            con = np.concatenate((r_nodes[0], r_nodes[1]))
            random_nodes.append(con)

            curve = bezier.Curve(r_nodes, degree=2)
            curveLength.append(curve.length)

            curve.plot(num_pts=256, ax=ax)
        #plt.show()
        #print(fig)
            
        
        # Save just the portion _inside_ the second axis's boundaries
        fn = 'li_{}'.format(_)
        ax.figure.savefig('./workspace/mobile/images/multi_lines/imgs/{}.png'.format(fn))

        cap_data = np.array([fn, random_nodes, curveLength], dtype="object")
        xmlmaker2(cap_data)

        #raw.append(cap_data)

        plt.close('all')
        
        
#multi_line_datasetGen("s", 3)

In [24]:
def exec_file_maker():
    counter = -1
    for _ in range(5000):
        counter = counter + 1 if counter < 3 else 0
        #print(counter)
        multi_line_datasetGen(_, counter)

exec_file_maker()

[[304.93784408  63.14235558  72.47246608]
 [331.92668318 283.72988575 224.79213585]]
[[ 60.12382039 232.87030941 397.60541631]
 [209.09477889 379.11169846 195.21398461]]
[[202.68344912 348.86449816 324.47229824]
 [339.84465496 346.06397563 113.30251361]]
[[140.0926582   46.42726409  50.49843805]
 [315.08990617 358.65278997  73.66288628]]
[[240.89319675 224.24870755 311.01168301]
 [236.25712052 102.12480591 277.09206853]]
[[ 83.98766076   4.17521262  96.00185055]
 [387.26034455 185.62772319 316.90261068]]
[[ 23.28133157 197.02534719  83.98764191]
 [227.32024978 301.57695436 249.9279392 ]]
[[194.72920112 122.28822689 279.44645679]
 [363.84398746  61.7312077  301.45899355]]
[[184.0055532  295.28107068 141.72880043]
 [124.4834175  379.42114256 177.62613895]]
[[273.11755022 296.42573891  68.64900445]
 [259.69671542  26.8373885  163.03469843]]
[[ 42.0123841  390.33507498 147.93715183]
 [108.38453292 129.33091952 264.93416985]]
[[153.15182032 363.61346719  15.46870291]
 [231.15951759  85.7701

[[  0.35817524   5.64935207  62.65493888]
 [157.40382551 163.36266313 339.99288596]]
[[ 43.89868464  58.46575173 290.13732526]
 [141.80619095 220.00037963 258.40191681]]
[[393.07812582  43.05900225 186.76087077]
 [227.82585166 275.42612969 393.90438722]]
[[122.38510562 277.24935098 114.76332018]
 [203.95018957 331.43704907 284.73801511]]
[[229.93101092  19.5326619  389.91280578]
 [396.50701744  23.05696817 164.10809089]]
[[380.78814231 128.75190672 151.45410248]
 [396.98334461  91.70008124 377.74045277]]
[[102.12749877 124.96366897 293.71118155]
 [131.35682964 291.04017762  38.60049927]]
[[218.77656149 158.59943068 194.87131405]
 [324.06346584 154.88701524 377.25526696]]
[[ 85.31188454  91.71129954 350.7472312 ]
 [365.5557015  298.06096473 233.57063597]]
[[151.0279956  119.14877882 364.3548947 ]
 [356.56638625 132.71499726 367.23100331]]
[[361.96406113 399.30461026  43.89761562]
 [327.70554585 207.55349909 166.49426748]]
[[186.98119891 236.66723045 205.96500124]
 [361.5439173   68.5222

[[358.77031378 146.6069088  212.40102869]
 [ 23.67751356 182.11731215  43.56411464]]
[[ 93.76427442  63.54050761  57.60589199]
 [398.06385624  36.89654945  20.60134198]]
[[ 14.27586918 270.77518947  36.27664581]
 [ 17.02652419  32.02694863 108.46532305]]
[[399.67946947 268.62942933 371.16492931]
 [156.16864019   2.84580736 347.36125689]]
[[340.10834168 389.06528634 309.12644658]
 [330.07239857  76.38747003 305.82363923]]
[[ 25.2568402  251.42263502 277.30117732]
 [144.5633405  104.43289909 369.57314452]]
[[ 69.53232513 132.98500078 278.1911593 ]
 [364.44816023 224.09585099 129.10987945]]
[[193.9545402  341.41687053 365.90194087]
 [173.94123489 234.45308555 192.38446296]]
[[260.36928584   1.66516197  83.62856579]
 [312.01337456  42.49011914 264.83287226]]
[[180.23856601 273.05772645  50.88491501]
 [ 61.55128397 367.74382595 387.16977223]]
[[ 88.71252728 311.66459751 231.63500065]
 [279.32908445 141.43458478 120.54989267]]
[[331.77972352 200.81131473  81.8446747 ]
 [ 45.76798139  18.3091

[[198.32687059  31.6291894  282.47580723]
 [341.39867452  52.19403375  71.86852508]]
[[322.56001126  98.02382353 292.73803546]
 [ 29.62774455  92.37418332 228.76595897]]
[[ 11.02235427 159.809174    93.12610261]
 [331.44812215 294.36016413 112.11325389]]
[[101.08924312 130.27849333 116.29187528]
 [282.04080642 126.17639377 313.71560723]]
[[ 75.07995451  51.36574798 316.54524838]
 [354.65395598 220.5613787  328.61912922]]
[[260.50877428 390.75085476 188.22120268]
 [201.08703624  23.53047379   1.60247148]]
[[376.86332681 285.4637829  119.20876277]
 [ 63.96507619 398.34648651 156.82095627]]
[[240.36871126 263.16591953 374.34624177]
 [ 45.88886159 167.98625494 190.23220279]]
[[385.35404387 192.23140075 165.75031361]
 [287.65978402  72.14543186 146.51705037]]
[[103.43308643 274.45918672  39.85684145]
 [305.05233666 306.73007828  94.52964002]]
[[157.24649901 143.08902261 192.09946906]
 [359.71293111 350.29192666 199.99824017]]
[[230.95597607 161.22218434  88.34289071]
 [142.14785112 359.1878

[[ 87.86234758 167.3984096  166.02901115]
 [382.38035419 120.84535346 201.95605929]]
[[145.44200052 138.68187489 338.22658481]
 [ 28.99435615 251.22831036 247.41016543]]
[[309.8356952   90.56251901 311.87585212]
 [229.84609606 317.69127526 244.03537484]]
[[235.66748525  13.64776314 301.11013317]
 [253.77035652  34.77784615 261.71218975]]
[[190.84270658  53.83268053 229.07816148]
 [227.04230967 135.41217202 322.02057768]]
[[310.35795969 288.18396969 220.45854158]
 [118.54727212 127.21659223 367.92985216]]
[[354.40255221 318.49078641  37.33021495]
 [ 60.17648149 135.52308279 271.99346825]]
[[386.00360988 389.21703735 378.1266021 ]
 [193.81425493  54.33410307 147.46477981]]
[[321.31340908  28.76412255 270.30331163]
 [385.40058778 113.01784986 308.14560693]]
[[245.28347982 201.31247735 360.74868794]
 [132.10784525 254.0819699  305.77101054]]
[[172.64232341  87.85075821  33.86171931]
 [390.24307815 359.4504099   50.60611665]]
[[179.08461226 247.04657244 258.21866911]
 [272.18459312 281.5103

[[196.54418318 385.30880466 131.54513845]
 [ 26.12071775 277.4643102   17.99866674]]
[[ 35.22583985  99.60244677 273.09910165]
 [224.81456047  24.58399576 311.79351908]]
[[316.34086021 248.01929992 220.51639071]
 [  8.12155977 310.83270564 164.76221411]]
[[288.3407988  110.011962   365.39348231]
 [ 65.92714449 294.10505929 274.91866793]]
[[ 31.9895128  386.12061717 365.28789852]
 [358.08456857 327.16784976 315.74148382]]
[[246.3628365  387.27923189 309.89371362]
 [ 24.85022231 261.56623993 378.10734186]]
[[251.20464149 305.30598726 240.39114151]
 [230.77124638 139.52769733  55.43356072]]
[[ 99.28199195 350.90916748 108.28808053]
 [391.14503001 183.18054108 253.80871648]]
[[ 61.82773341  45.96384832 101.79898356]
 [220.30686525 215.77144578 330.85993972]]
[[272.75203201 330.80307268 306.42482062]
 [370.64660236 214.91521175  31.28951819]]
[[129.09081423  91.72001996 187.61565262]
 [ 24.40213645  56.8379579  284.34075479]]
[[ 56.67721476 258.75111825  90.15057531]
 [370.54136217  52.4702

[[168.93413429 155.38987951 171.74118592]
 [310.15167921 364.66695682 336.90192208]]
[[273.86309555 251.37046463 111.68219443]
 [256.361035    92.41040954 280.78986762]]
[[ 25.20583479 118.04763013   1.42641684]
 [241.63849196 394.82458214 197.4704263 ]]
[[312.92160603 165.40365587 211.99728141]
 [228.80167005 327.27493688  71.35957069]]
[[ 14.98620978 385.80336294 228.82301897]
 [ 54.85452411  51.40855583   1.20105458]]
[[207.69966749 238.32237654 241.83095716]
 [222.3155603   35.57240088 321.4782054 ]]
[[118.25391796  60.96472506 220.00286095]
 [116.57339503 166.90373978 293.80642051]]
[[112.93870152  82.00245138  97.5677937 ]
 [ 40.10869853  87.09015633   0.5400542 ]]
[[167.12150989 161.43864336  33.5645136 ]
 [107.89487307 341.68739624 135.9740725 ]]
[[328.64138608 302.33054981 131.59011907]
 [358.21613185 396.19349166  45.31443622]]
[[159.8678293   73.52793136 376.95635833]
 [327.83288708 381.68296152 245.52558192]]
[[184.22163598 156.26881004 208.09401625]
 [ 53.85965674  71.6933

[[224.95288893 335.11650574 280.47971971]
 [ 45.69283218 320.31486202 211.09230865]]
[[293.65939514 189.62284147 397.30176129]
 [396.48886749 283.82149531 276.00534452]]
[[ 48.19285724 359.11511998 188.43555792]
 [105.77129328 140.16392188  62.03550173]]
[[306.70173663 335.36714486 178.63781579]
 [ 75.73246174  71.59570817 280.60517904]]
[[ 73.63963272  58.64090877 324.53816062]
 [141.78475585 247.56604939 121.15716081]]
[[283.514824   361.28723597 308.09216888]
 [237.66446852 304.75496391  64.79619652]]
[[ 80.67147999 204.91982857 161.46026641]
 [ 28.08082315  49.88403571 196.74504056]]
[[132.86446136 243.10519775 392.3378642 ]
 [149.73776942 137.3419498  327.53639364]]
[[  3.27231662  78.08502314  58.6733099 ]
 [132.48756293 367.18092065  48.96678858]]
[[373.5666219   16.37276829 353.42350678]
 [ 75.68329917 173.74257346 362.79600271]]
[[157.14062841 157.57514379 177.87436926]
 [136.11974035  45.1521517  240.85767668]]
[[302.14321579 384.82858233 313.03261449]
 [182.35867995 331.2461

[[ 38.58994596 127.75228141  83.57809799]
 [ 19.50563476 299.68628737  40.1824963 ]]
[[238.73612919 204.15984519  77.61359282]
 [356.85727926 241.66438669 331.90242802]]
[[275.92249499 337.73486322  61.97903969]
 [ 98.77022908  42.14201471 146.32800103]]
[[ 97.35326179 184.99369449 180.55986196]
 [167.4764363  227.6210982  289.69807934]]
[[243.3310869  257.28374513 277.62749484]
 [ 78.48213028 394.46606348  94.37414742]]
[[165.1508255  398.02550291 334.99589494]
 [215.03642378 349.60608941 332.09441556]]
[[312.68500057 126.34092878 168.24275643]
 [106.52503434  47.41970376  14.91776111]]
[[289.7920669  358.94037982 144.67920649]
 [332.25488976 286.02120262 349.22524779]]
[[317.70768613 176.70757195 246.30324997]
 [171.14202115  59.34729791 133.04897688]]
[[160.46425061 258.7446556   59.87217583]
 [291.07314513  38.67111534 178.34177503]]
[[380.85962641  45.77809177  65.14665056]
 [155.3599483  187.73325639  93.5538067 ]]
[[354.42145727 298.8389827  234.85739411]
 [194.42231587 196.4950

[[182.98952968 192.34590389  85.73973375]
 [102.65414909 353.00019416  45.560743  ]]
[[282.46280524 344.26757255  74.7780331 ]
 [274.81735865 330.63929803 153.04522601]]
[[107.98039656  32.03287177 114.72712482]
 [ 77.82540284 209.21552513 270.24796501]]
[[118.92343826 330.11050351 331.45636114]
 [330.68238782 277.20538942 399.93535363]]
[[ 44.42168399 366.41428843  21.49468077]
 [337.17660284 256.08115973 259.28618841]]
[[101.93909883  82.27063803 182.06118523]
 [321.1571797  119.92929596 169.78907104]]
[[ 93.44853173 180.30621106 290.86772501]
 [ 59.57446987 149.64109675  90.9436684 ]]
[[149.9762049  340.58762769 115.64903174]
 [317.7133051   89.3000901  159.24214936]]
[[181.54873726  40.79773248  13.84263791]
 [  8.21714895 132.79924786 329.44842185]]
[[141.30314898   7.79383476   7.56209267]
 [204.58221022 247.75839247 163.14422336]]
[[197.71052508 112.93370951 284.70201438]
 [ 87.14600435 380.00905691 158.01402006]]
[[254.76159562  50.96901584 131.690348  ]
 [199.44246597   3.6268

[[180.98064992 288.26721681 305.21959926]
 [150.57150929 262.71851353  33.24623561]]
[[269.84940695 387.74005272 269.08070333]
 [188.6095101   70.09773471  79.35661124]]
[[390.76150159 222.41388228 212.71883821]
 [258.52958629 262.94588567 121.46189608]]
[[ 89.78879685 115.27428316  98.77133073]
 [ 18.59151666 341.8304075   96.39415749]]
[[356.83810057  79.73360461 159.67248606]
 [ 99.98332974 174.38961646 391.23945939]]
[[368.08304584 363.34363548 259.75801986]
 [224.92636582 270.70556203 346.95683526]]
[[378.56120803 376.33326107  50.44260089]
 [304.17282704 200.43068982 221.64378624]]
[[143.28949149 374.18197114 351.90520468]
 [191.58866893 383.17157754 222.69970147]]
[[ 29.2994435  349.78800024 238.60166311]
 [291.14945791 182.51689673 257.53555522]]
[[381.77994912 170.74033805 143.35229194]
 [195.49264977  19.47368677 391.61551831]]
[[ 96.85018319 369.66118127 292.03078111]
 [159.37073823 183.35820452  28.60151864]]
[[ 67.03469432 362.02715336   0.5224047 ]
 [188.06586404 314.9778

[[136.68579095  16.9974012   69.99164732]
 [171.71475691 322.51776528 203.63166009]]
[[374.84123575 349.15343176 265.93465821]
 [171.73286139  22.45794307 187.47663304]]
[[297.305837   320.84076401 190.72137903]
 [ 77.18953419 239.4956272  210.62136199]]
[[342.98832607 306.66135735 137.34774381]
 [371.77126716 135.24546014  90.17634452]]
[[361.60225643 331.59117069 390.24613701]
 [318.88249756 311.17748545  29.16873122]]
[[294.29604993 189.90157368  97.45906432]
 [ 43.48280065 240.82860188 135.74572792]]
[[ 65.35794587 344.25493769 335.6791276 ]
 [196.8494415   30.42203361 399.66562035]]
[[200.3796795   30.54027003 192.45475866]
 [163.97057504  88.08318353 237.94661699]]
[[264.36815554  41.97051857  73.92829447]
 [187.46064511 284.49623661 255.97495317]]
[[107.06871416 321.95658874 258.16971611]
 [129.94327459 179.80765976 125.32948772]]
[[ 36.17480811  10.33508797 296.24353169]
 [ 19.36455902  89.27848418 233.58917008]]
[[335.95631687 126.46612073  57.97909351]
 [ 90.6367213  303.2751

[[234.24560976  21.78142033 305.89474277]
 [ 94.44253211 367.41346147 210.7884789 ]]
[[143.87464607 280.25088555 223.95225023]
 [211.70457834 222.60910284  73.93595051]]
[[ 45.5235685   62.79021898  27.01521516]
 [172.17837763 391.44629865 330.11311536]]
[[268.99968166 195.02495022 256.19765191]
 [161.13246107 246.97322297 306.14379327]]
[[169.07137908 155.17630684 221.9584306 ]
 [283.42883435 261.9631094   56.24721733]]
[[  3.41986363 384.73533776 242.50315961]
 [ 72.19607404 111.33471462 350.96276591]]
[[ 23.00284942 333.06463543 272.52832232]
 [165.14629655 205.59283264  98.5946584 ]]
[[370.28996575 161.89732467  29.87846291]
 [ 60.5682163  239.03142241 248.70890387]]
[[  6.79564323 348.16212864 225.70236458]
 [ 54.30340356   9.58911847  42.13876464]]
[[288.92177999 109.99406457 149.56774122]
 [132.36027042 216.36761429 201.37561296]]
[[186.39070177 240.62005198 194.30200533]
 [ 88.66185654  87.70758662  47.14450297]]
[[ 73.31881698 257.97932962  77.4651271 ]
 [219.96234404  38.5321

[[306.09403684 392.47763168 203.83981135]
 [227.34790544 125.90160401 293.0774382 ]]
[[203.67653613 158.47328673 172.87252667]
 [ 26.52483125  27.10923398 380.25852427]]
[[ 83.18588525 355.06625299  29.99676246]
 [149.96575899 252.6865388  186.32207334]]
[[275.12589457 192.93727886  85.61697329]
 [112.35049379 396.58246418 369.0915095 ]]
[[390.61392134   1.99833996 332.36612761]
 [173.70902048 345.11163469 120.50441479]]
[[ 45.35787876 160.9914448  297.69493156]
 [215.93986289 387.38369532 273.59159173]]
[[212.15869925 215.80063097 373.23254196]
 [353.23476255 324.97046303 300.2142886 ]]
[[190.63945991 391.82493011 115.96753115]
 [ 31.22545017 286.71562789 249.18934635]]
[[316.51059149  47.93516308 179.08946511]
 [300.36018376 108.51866208 372.18625331]]
[[125.82277787 382.71682906  31.97888851]
 [161.60872505 225.87718344 282.30670425]]
[[329.2593503  143.62654271  89.95239385]
 [337.33967478 117.63183495 355.87754884]]
[[243.42440821  82.75708566 124.44332212]
 [ 74.78268006 264.5612

[[188.58879159  70.07113327 327.98580992]
 [380.45987156 261.50544768  37.81368115]]
[[238.63971357 149.95949096 121.31956145]
 [ 43.27343584 169.78605615  66.43058354]]
[[359.33999932 283.03344728 193.30550865]
 [ 60.58387109 143.1796294  280.7600636 ]]
[[239.2625106  216.02136809 151.63396771]
 [258.02653538  30.86921205 315.04033296]]
[[263.59425999 106.14297285 170.52010905]
 [ 91.67796524 229.31332232 140.7183866 ]]
[[231.40201516  40.15785782 235.49187087]
 [ 74.14444885  20.14360333  49.37774831]]
[[127.1233337   77.15812546  58.72284569]
 [286.7799142   78.13616108 368.48728682]]
[[198.0720374  197.20473424 130.97537451]
 [236.21963856 227.51493919 144.1583376 ]]
[[385.35373156 241.56388866 139.81116355]
 [199.91991467  50.63354743 379.52589386]]
[[ 57.69041103  68.52332049 105.55330592]
 [239.92539985 312.49474915 247.37746985]]
[[354.32194906 238.92973639  75.70628305]
 [217.69459085 128.27500289   3.72703939]]
[[194.07595166 112.58337887 192.50507501]
 [ 54.60232247 287.0478

[[ 85.31049363 140.87861227 189.93489596]
 [342.58935479 206.94522181 330.83989147]]
[[142.80834708  24.0740043  125.61342497]
 [326.00758242 308.60030138 348.61739429]]
[[167.52347049 115.77991617  64.97833005]
 [121.8262144  383.7990352   51.71577519]]
[[225.59665739 290.075567   107.91209926]
 [325.24302318 175.04583759 154.70033433]]
[[324.26000957 339.19948638  43.91262194]
 [ 31.21169677 239.4597493  260.8903265 ]]
[[101.33950623 297.7411796   55.64076579]
 [218.53795514 100.45583826 230.2215615 ]]
[[ 66.79547112  36.41092013 128.40262057]
 [297.53002707 129.9124706   44.70288672]]
[[  7.78827888 121.35007534 256.5859624 ]
 [327.2814836   30.5466899   60.76833485]]
[[146.20619254 168.86569974 143.24486173]
 [364.9331572  318.39684385  86.06707866]]
[[175.49300279 286.14961299 245.91446495]
 [108.81157083   6.72815211 213.81525207]]
[[330.88934893  60.74884705 391.32276235]
 [  0.87626644 145.72580697 360.45833046]]
[[ 72.91676964 392.49108603 127.46467456]
 [ 70.0016131  327.8795

[[271.12388292  28.22483657 244.45571748]
 [ 97.53668117 162.75548779 276.96984036]]
[[245.82765061 371.42565179  11.09002253]
 [312.72208004 351.61253301 361.00234565]]
[[ 11.8529076  394.47708209 246.71069202]
 [271.7298576   69.38742015 235.88442529]]
[[127.2022783  161.18886792 365.2888358 ]
 [185.04166048 131.65219251   7.75629554]]
[[130.46191732 347.0595542  356.58157561]
 [215.70793547 378.98639396 247.10134658]]
[[175.10515301 274.54004241 259.14271893]
 [134.54741592 214.13090812 127.24106178]]
[[293.26543656 157.74707003  75.73120057]
 [295.43225562 139.87012094 391.88394271]]
[[167.20857058  24.72554908 192.23568775]
 [ 98.34742611   4.9853777  176.38884279]]
[[359.54979396   7.11829878 282.50824998]
 [215.17269285 205.73993935 303.95224329]]
[[ 97.23703914  35.13732174 160.33966709]
 [256.22244304 136.67650361  76.50478278]]
[[ 18.7589592  168.18938889 358.27261387]
 [386.86403245 141.90707487  17.96476962]]
[[341.91174036  10.80510664   9.72814441]
 [ 59.31611111 110.5581

[[392.77662167  75.30271606 310.26500601]
 [148.1596659  320.63471982  60.19701362]]
[[ 37.59721022 215.0522461  165.72683427]
 [229.30285898  43.32557279 103.09535313]]
[[228.88344422 121.37970716  95.93560579]
 [ 42.94201849 182.63672214 212.43896988]]
[[ 89.96089027  91.06628592  95.71346392]
 [199.80061484 371.45519773 105.69162847]]
[[256.9237977   52.56696993 355.60439647]
 [161.78784846 396.24849476 121.2115674 ]]
[[213.68048449 298.14536218 230.57381954]
 [131.20788975 217.10326483  72.14265316]]
[[ 35.01771372 105.76635698 127.31701205]
 [362.06722433 286.80146455 133.14221209]]
[[368.58676559  61.98935719 297.998807  ]
 [ 52.66379934 231.69280157  41.09365448]]
[[130.24603559 233.47782949 102.88609805]
 [323.56497779  67.84891847 376.86411058]]
[[312.53737249 240.84073829 217.79060835]
 [252.5353535   56.93429935 228.3764802 ]]
[[312.68772219 274.82232342   3.78801566]
 [378.79472166  43.87398639 357.6973235 ]]
[[ 54.77068344 309.06965625 185.13040196]
 [145.46576978 378.0648

[[  2.23479778 375.18475561 125.86635326]
 [107.08715171  57.20815686 306.73662275]]
[[ 84.22274982  17.30092467 375.54082555]
 [125.70244306  97.37292103 355.27051884]]
[[ 47.35484141 258.6275496   87.373471  ]
 [118.05838632 308.95211355 235.817141  ]]
[[319.45476094  91.571615   233.04913655]
 [279.40083268 264.11118425 209.32659021]]
[[ 45.29365122 228.42202612  92.05348346]
 [256.14465101 281.14433351 346.18567198]]
[[ 77.63386375 270.87047196  45.72010004]
 [340.92016495 292.96306781  99.71532468]]
[[262.00626505 245.06998695 142.2907079 ]
 [ 13.47880963 109.40564216  81.91675614]]
[[214.58455395 280.35651236  25.34917821]
 [337.81274868 249.44388898  97.6258696 ]]
[[223.36596053 279.48181266 172.42733339]
 [190.1013605  263.23867499  24.15824196]]
[[ 88.6913766   17.69774641 373.4771973 ]
 [ 50.06417033 271.86338138  84.63805722]]
[[222.15315556 104.97355079  54.85893392]
 [360.10239985 201.88217337 360.0801958 ]]
[[201.80463717 158.72659531 318.67056703]
 [253.23651268 136.5587

[[192.19451213  52.78735946 255.23514594]
 [241.02349024 358.56662357 322.98222934]]
[[324.0396248   82.13548936 227.75563738]
 [289.31949981 281.72399171 182.95172433]]
[[ 15.58822934 108.64724267 399.25044906]
 [363.38248809 351.55663968 395.44382887]]
[[ 30.61201955 298.22150646 340.77136997]
 [ 25.97632957 107.06605445 336.15516748]]
[[157.0267966  219.31176746 319.03711785]
 [218.13996287  92.90668134 254.18651824]]
[[ 50.89401204  87.85055713 305.38091175]
 [170.27610449  90.35710025  84.14396335]]
[[233.47512291 346.80940143 228.81024319]
 [ 57.10336601 338.60008801 315.57822166]]
[[250.1712077  374.88414999 108.24547072]
 [ 39.15286515  22.81742433  11.6948031 ]]
[[158.53279965  94.15926608 280.46588732]
 [376.006047   389.29387223  53.89379778]]
[[ 79.56650597 375.30443327  39.30745573]
 [ 97.96393829 304.90548883  40.79399557]]
[[325.66427108  86.71392867 162.55621244]
 [338.69838388 386.62049826 191.39093653]]
[[329.41648923 387.8419596  394.61342655]
 [ 32.86002987 104.1528

[[160.34333385  24.06259073 188.03971376]
 [ 93.04958692 160.05899982 311.90266537]]
[[299.97801094 194.80086009 207.66027293]
 [290.5649731  301.2468806  300.28663696]]
[[  3.23443595 141.91519784 179.76657041]
 [ 37.39173768  48.74794166 358.2746169 ]]
[[9.15773678e-02 1.02184308e+02 2.66009779e+02]
 [2.01022487e+02 3.52022916e+02 3.25013663e+02]]
[[267.30982093  78.46208716 351.47434668]
 [209.75415919 207.15431293  94.08854267]]
[[363.41561172  77.80090729 279.56688036]
 [219.5670484  355.45970397  44.19914677]]
[[ 84.31809402 301.918978   333.88591001]
 [ 53.79389928 216.85878631 393.31043198]]
[[ 85.56271247 113.21810208 342.79520099]
 [326.29927806 302.2928348  147.40499032]]
[[ 44.5635021  161.83028372 368.18916694]
 [385.52271348 273.48493423 322.0488294 ]]
[[115.02145471 212.65282131 227.72847826]
 [ 66.38407274 289.72123117 162.61473008]]
[[ 98.87639614  25.51633322 376.3572668 ]
 [285.90149449 286.81828946 229.52126868]]
[[174.50608674 247.98734055 179.00533185]
 [338.72533

[[171.79516233 100.55538264 221.31670799]
 [160.94441379 277.26409293 271.11109649]]
[[ 68.460323   158.40179154 367.79532931]
 [362.55890062 174.26890472 170.48720559]]
[[ 48.3101473   49.40626682 380.92488774]
 [293.97777798  98.41226943 199.52140709]]
[[281.66213714 232.4079412   36.58087096]
 [298.96048965 258.47118794 147.94545738]]
[[ 51.52077037 397.59069763 387.45206166]
 [118.81246536 390.1865122  173.63591814]]
[[260.51203342 237.69343147 252.42057152]
 [ 42.2506403  122.26080688 150.61980524]]
[[ 69.3882503  121.12276918 368.93749174]
 [ 35.86782675 267.84040348  13.05747248]]
[[251.93431665 223.3203376    2.59788932]
 [130.17676713 212.67544447 226.93170755]]
[[  7.12314279 364.03917091  49.66374986]
 [154.44355196  27.41512422  34.32135734]]
[[ 71.0032147   77.63678795 164.49351659]
 [341.35792323  93.65323969 390.48293703]]
[[ 83.27849812 371.36051337 343.30989756]
 [ 67.57107174 112.29119306 250.83168442]]
[[373.08964351 331.17259212 280.02928774]
 [144.56908753 265.9782

[[ 84.20259227 327.39397298 127.64231394]
 [331.04641755 327.07627292  41.39458477]]
[[307.8949709  260.3131337  113.00681151]
 [207.64372344 364.82138983 103.81581633]]
[[159.12046703 265.64876495 260.74022981]
 [249.13362789 349.61765623 252.11932949]]
[[ 51.83264018 218.87183872 358.06434236]
 [151.15961158  61.25617334 368.09431192]]
[[ 79.67063557 375.17934006 110.9012202 ]
 [269.12459386 281.25108823 277.62285978]]
[[392.59818521 106.14721167 252.01583451]
 [115.94196751 310.49725442 207.67389766]]
[[323.45204741 222.06427148 173.59376143]
 [317.60981778 295.68019197  60.41585443]]
[[309.99904433  66.91710602 356.00263002]
 [343.7472564  286.22832924  67.78680126]]
[[351.65167941 221.30406391 190.30582492]
 [217.06594774 321.4344142  304.82258692]]
[[363.71483223 148.99379588 120.31100461]
 [ 64.49688366 358.00615685 332.27417877]]
[[288.04155982 329.06023263 137.31892901]
 [ 25.08108907  34.27314604  30.69417145]]
[[ 27.2618241  374.88399992  78.74842795]
 [193.87848871 315.4919

[[108.69622432 234.20706584 282.80590397]
 [339.52457163 236.14503423  42.63927086]]
[[189.95522995  95.02749736 347.1597576 ]
 [133.04244933  20.06806713 178.39346765]]
[[230.99550037  15.96797791  39.78363728]
 [ 77.52147193 288.51528717 307.23931011]]
[[309.17600764 262.50379888  51.62249082]
 [ 70.74552659 277.8871113  287.5617937 ]]
[[284.16519947 184.70710906 105.97440594]
 [211.66347842 136.39727043 179.96436724]]
[[385.18690711 178.0749588   44.95118328]
 [277.3972716  197.16351141 245.40264938]]
[[375.48181746 320.44553296 246.02484004]
 [ 70.31457492 122.76331504 381.81672985]]
[[317.95064294 104.70247036 379.78621586]
 [199.8746294  120.88570758 119.44304456]]
[[ 81.19571213 389.43816231  49.67791481]
 [ 77.88376277 291.53382841 244.33792465]]
[[200.78644706  48.18620418 292.60164651]
 [289.89771492 252.20932983 340.62593858]]
[[113.99483833 185.57523665  53.52436817]
 [394.22980729 119.52367227 391.49715972]]
[[162.70209956 303.29569287 270.35100425]
 [ 67.48131314 134.6722

[[192.17791586  22.65855581 374.58516663]
 [385.06255995 257.0868541  149.15235537]]
[[ 37.22742012 375.35738758 221.05907781]
 [247.74123131 117.31110125 325.93294262]]
[[267.3312859  273.58050474 123.60566268]
 [ 47.483205     5.76961276  15.49490304]]
[[356.47787241  68.55174209 197.88569328]
 [314.85880959  73.64756499 360.9192263 ]]
[[ 71.43633314 116.90037832 264.70731408]
 [281.88442213  14.8209275  242.5828372 ]]
[[ 40.03781319  45.63268419 254.16153482]
 [ 24.95219906 221.39533737 112.46292689]]
[[241.93342203 143.83066971 237.89074761]
 [294.82496957 244.00548329 379.78939317]]
[[  2.39164428 370.41300549  74.37669485]
 [304.19033532  67.48445477 164.93577366]]
[[327.18940429 190.20018566  20.54845273]
 [214.68909292 116.4054797  314.83290933]]
[[ 46.93511199  93.02349918   4.79660359]
 [244.26682091 212.04247691 382.5143403 ]]
[[ 72.08269591 260.41568066  94.74601658]
 [327.74217466   4.39033105 146.67166716]]
[[ 81.71900396 290.92003823  64.13300102]
 [120.33890266  48.5425

[[377.38454922 265.31475243 136.06505519]
 [247.3002935  164.96894988 341.91242456]]
[[239.03103342 228.63931735 390.08755286]
 [362.94837499 399.49581408 387.07227595]]
[[342.27778508  19.11283402 278.9085915 ]
 [116.14628492 300.74819954  13.3011601 ]]
[[149.6706593  311.53967943 193.19903269]
 [168.3995404   60.58635672 395.60542429]]
[[355.83069178  94.07195004 325.40855667]
 [ 14.85145474 121.92756423 318.92387732]]
[[143.57934971 102.76046563 100.15158314]
 [112.6285934  102.36577203  61.49425568]]
[[273.899562   224.39533846 173.6936935 ]
 [325.80773213 252.22573936 173.23521962]]
[[351.47490146 250.49921753 180.6209489 ]
 [181.62579285 398.59022626 123.33747334]]
[[272.78444052  12.64591957   8.56275042]
 [201.18846698 127.08606022 305.4236769 ]]
[[191.80505811 333.43919482 127.67619566]
 [121.57872722 154.76048912 286.34440146]]
[[226.18045955 174.43476123 105.33489391]
 [361.14260509 197.16669411 179.31742566]]
[[242.95324464 196.78781952  54.42360659]
 [ 29.41935841 114.4257

[[277.48222805 318.97827992 111.21269556]
 [294.1200215  150.20892172 273.11244734]]
[[179.75124907  94.4666273  169.60423597]
 [  0.19344291 114.3003982    3.61821334]]
[[177.7175448   75.79813125  98.16535572]
 [228.4623919  186.50638918 246.22891791]]
[[307.92625186 149.49394712 228.57308082]
 [334.52027424  21.29354054 198.64396935]]
[[305.66002023  31.50838438 111.79129667]
 [176.63062942  41.83630782 334.67394898]]
[[180.13157921  61.59870266 245.57898606]
 [348.43011884 341.39146041 328.41092979]]
[[ 31.16733884 363.80065176 312.90371003]
 [378.81683213 328.25010628  49.02823514]]
[[165.41388269 148.06999403 347.64915604]
 [340.93494816 253.20107678 132.11366121]]
[[336.94787965 321.25113855 132.9904673 ]
 [ 57.7664895   56.82567257 165.56811525]]
[[177.25971492 108.14995139  99.41079629]
 [279.01692966 388.34869797 195.4757405 ]]
[[266.67995129 197.60907959 136.95533076]
 [273.15958596 156.81069428 277.03107299]]
[[ 63.35535811 280.13517368 192.9321236 ]
 [187.33972609  68.3671

[[ 95.11686908 179.15620846 155.49806153]
 [ 45.24461391 289.28594314 209.62156218]]
[[179.69296357  96.48605607 145.65508434]
 [289.77552713  99.25062374  69.82741947]]
[[ 21.06334582 131.00589844 315.90122824]
 [209.69578914  64.49056638 147.12235162]]
[[351.73351472 388.1986222   66.03488904]
 [320.31138084  39.25529474 257.14048983]]
[[333.27941464 115.55962867  64.85687064]
 [  3.3732983  383.80110001 101.42837385]]
[[395.08707059 338.84698684 287.19573545]
 [  2.18758728  42.35666453 132.6445356 ]]
[[316.16463679  89.48123553 342.89035525]
 [ 64.52781505  24.08605719 150.13863409]]
[[ 82.99257987 305.03621517 142.99087461]
 [222.3397434  275.49545038 282.63073833]]
[[ 95.29337688 344.30108894 162.38562404]
 [ 74.4998429  166.92362204 302.29750723]]
[[244.9557076  289.91805013 123.13820304]
 [235.85857364 256.64461931 241.46953293]]
[[129.32334019 237.5466065  193.08770674]
 [185.32024017  50.93288073 399.30849139]]
[[362.17846496  97.65681162 198.59712508]
 [ 18.68094706   2.4657

[[ 33.80404522 254.07716678 185.00712101]
 [362.18655395  76.86716849  50.45715941]]
[[390.96334749 103.21162988 232.78897663]
 [198.90176414 243.18270876 224.09966345]]
[[ 62.754768    37.56735526 224.00451185]
 [ 17.8749956  383.8578508  394.34394401]]
[[328.57224814  18.12343054 188.37719586]
 [260.32949443  18.90368329 354.72407958]]
[[308.65540898  94.21205925 358.9743263 ]
 [316.39808132  85.69857859 105.63633932]]
[[343.21208553 349.7897291   48.71184097]
 [121.17357158 350.77414824 326.22463918]]
[[357.6679431  110.1937473   26.41177718]
 [262.61146048 175.45748281 381.91130471]]
[[163.18360206 205.58709417  15.61453268]
 [154.94960478 323.42764628 272.36869253]]
[[312.40884978 277.15125218 160.29675427]
 [ 96.92227276 373.1902069  239.32144845]]
[[371.21606001 289.79581988  20.11278578]
 [169.39901662 179.13549223 269.79602853]]
[[338.90045614  76.82612343 367.50341565]
 [235.48995363  90.79770414 245.45682575]]
[[316.21783824 314.85094528 207.99288449]
 [329.86205987  38.6936

[[184.03189049 116.03504909  79.02937244]
 [ 55.57994675 113.11009858  20.43711253]]
[[ 33.61036128 247.26261818 240.48723733]
 [200.7483031  355.32434247 334.8491032 ]]
[[246.15485    377.68319565 372.00166282]
 [248.77224035 302.46810653 128.98986195]]
[[248.56182792  97.31678013 394.78639006]
 [394.95022837 246.74411861  22.67859995]]
[[ 47.69581114 244.52259118 119.56116562]
 [107.40475237 305.1235173   44.16554882]]
[[348.27271356 241.66178224 343.02592577]
 [366.93657168 376.17764497 273.42504189]]
[[132.41535389  14.90853    353.4941978 ]
 [281.76778225 153.25477047  54.74321127]]
[[265.60881357 176.12235202 184.93901482]
 [ 45.24178175 122.82800131   5.43313453]]
[[139.46644399 279.6911965  148.80926356]
 [201.63180373 150.95535471 266.98300271]]
[[117.64757613   9.3660889   91.38563857]
 [176.30730643 143.18074779 363.18912785]]
[[388.4685637  309.43388797 241.58500492]
 [ 11.4458663  313.1419597  270.49063305]]
[[255.5051496  208.2807764   72.54624509]
 [ 65.66957453 158.4585

[[173.18872173  62.68255776  50.60239342]
 [191.44023116  78.61657689 348.91730194]]
[[198.38075498  51.10883883  25.38734593]
 [315.63190125 244.45214912 346.24167476]]
[[162.38247088  99.83461811  32.78177575]
 [285.99698009 354.01511477 155.43105632]]
[[145.18936739 248.23756344 207.10688694]
 [177.00000099 225.98591144 126.96333768]]
[[255.85101448 257.94405445 123.03655298]
 [397.42931475 106.83793856 396.17088358]]
[[121.59109537  46.51553438 304.83110135]
 [360.64896991 265.74926527 210.40396479]]
[[ 25.20794566 165.7578543   98.13690499]
 [284.33120771 261.61901975   8.30911771]]
[[358.99835412 376.92368381  92.4788688 ]
 [158.40171282 100.47633847  37.2624307 ]]
[[ 33.17676882 382.62720568 184.92589468]
 [196.88985888 240.23246327  10.55968972]]
[[326.12741998  35.34486347 140.55937583]
 [109.21489417 340.80313732 280.73996847]]
[[ 27.06845922 242.23342951 197.3032973 ]
 [349.4726492  161.02216984 215.25447643]]
[[295.25991218 232.5893381   77.74294625]
 [172.80948978 240.0142

[[248.14629947 101.49105828 186.67790358]
 [ 31.64107655 243.85613642 129.18089573]]
[[250.35062249  14.36564662 179.49529282]
 [325.77547091  39.90380523  13.12180902]]
[[291.5650489  194.67593317 287.01992473]
 [224.85119317  47.52552917  59.52915511]]
[[113.57388855 136.00773421 368.78658805]
 [259.25892277 107.71617091 331.87174974]]
[[362.47076502  62.71679193 128.96179889]
 [120.74564202 372.26790095 243.80424185]]
[[295.41244728 268.43165565 263.20539437]
 [ 81.98523317 145.92805685 270.34833595]]
[[278.36634232 257.80777369 173.4435699 ]
 [276.53088728  88.45247739 149.69763704]]
[[242.09359516  47.86312202 299.33310186]
 [144.83524261 184.654436   371.90590364]]
[[270.33358855 276.6070891  120.52332063]
 [ 58.88681918 139.06297827  15.79818909]]
[[ 93.6120053  299.61666547 356.610502  ]
 [176.42928153 123.32587267 389.17436278]]
[[294.38228849 292.87908056 312.8211854 ]
 [291.42721283 242.67844504   4.72856554]]
[[247.92719756  17.92655266 100.1926239 ]
 [201.92823454 339.1723

[[ 31.43782925 100.45441428  32.33369072]
 [347.73784406 321.58139661 270.45542596]]
[[354.28733872 211.63897392 286.04392506]
 [385.4717599  118.26816822  27.61135611]]
[[372.82924172 229.88532508  17.0100709 ]
 [ 62.9404296   22.04447672 350.41095737]]
[[176.26297492 319.78096992 290.92002034]
 [206.21368771 246.61070569 304.28409866]]
[[276.7774855  284.11269111 323.9280262 ]
 [126.51187352  24.00436986 188.98445308]]
[[343.11076149  28.92645061 138.69766293]
 [ 83.61082426 376.24647667  76.06425799]]
[[153.745336   338.77100535 142.48695741]
 [391.30483037 365.66488557 377.33386043]]
[[328.99275791 332.00918067  27.48782284]
 [157.14675193  75.22891169 369.66424111]]
[[235.83026477 337.44905135 129.57443564]
 [ 30.42632209 112.60136767 246.45124088]]
[[356.53727488 153.199857   185.98346203]
 [367.62451126 284.93280496 154.77719563]]
[[224.94106889 177.2061516  323.21716598]
 [  6.23831146  35.95699804 298.36301352]]
[[363.29722485 286.80880228 183.65300144]
 [115.75086808 183.9303

[[177.43215046  64.35184944 230.11668497]
 [315.50778141 123.47665204  14.56971348]]
[[230.17861616 366.53890541  22.19546739]
 [180.95419095 187.75721414 294.65235933]]
[[399.5719563   71.88741958 369.38590217]
 [345.07682824  48.01083216  80.96820205]]
[[333.54634376 306.44253757 294.40717233]
 [335.8065428   87.2839805   25.55137156]]
[[368.79044929 341.44126829 154.86836687]
 [363.24635665  88.69619283 284.31543643]]
[[369.95409905 340.09350718 324.77085926]
 [ 86.88532201 310.03323887 397.45344927]]
[[252.35983248 391.26836917  25.55886684]
 [390.94639726  23.36843171 243.64453801]]
[[110.70149857 322.26483963 173.90434381]
 [192.21340756 277.39971057 345.58166761]]
[[292.68546076  63.63101398 128.6028409 ]
 [311.67819931 308.42306876 370.26146263]]
[[ 83.18610882 201.45752582 197.07824797]
 [389.32132717 180.69575672 181.50788067]]
[[322.73315768 281.77505639 372.74490278]
 [216.16609848 376.55926333   7.23165111]]
[[251.87014987 343.74705623 377.12955037]
 [ 94.01618226 214.4673

 [ 63.90678411 236.42538466 312.72525339]]
[[295.57919881 306.13028658 199.4165588 ]
 [ 74.71301873 271.3833289  110.5396412 ]]
[[ 22.26635786  67.72673344 228.04090934]
 [ 62.92630299 198.87067164 357.16502107]]
[[  5.79725515 203.45969928 245.84291094]
 [216.49325735 268.91307467 226.50264694]]
[[255.53190667 246.07457298 191.28622505]
 [218.4652969  268.18774385 395.79107872]]
[[112.48162497 269.00855883  58.57770562]
 [ 29.06746218 242.54698825  48.10288433]]
[[114.07908142 163.32951774 361.32109055]
 [ 26.42741186  49.89560154 176.11984872]]
[[ 57.51434603 206.15675494  82.01210874]
 [197.40565152 333.91273951 242.26810084]]
[[213.41940999  95.7627889  109.41826075]
 [256.20153528 348.13185557 297.40602459]]
[[235.15594413  38.09056987  41.46556468]
 [348.1349693  245.08416475 380.81078029]]
[[ 49.36898915 215.50525577 331.87903938]
 [398.90641028 389.14294047 217.91133211]]
[[378.81672106 186.205153    10.54693426]
 [364.99677648 328.99691609 234.45445447]]
[[270.79580312 356.389

[[236.2025428  176.05495851 165.29225303]
 [253.39719791 151.60685447 104.90354461]]
[[ 66.9268461   65.88763053 277.695728  ]
 [117.19001815 259.97989352   4.69961895]]
[[226.38728845  92.04977187  69.69185862]
 [161.8167371  288.92584592 144.57845014]]
[[298.29938365 147.44642004  79.45609409]
 [285.24391416 340.56968099 285.68857972]]
[[144.27781617 302.58663616 319.2724447 ]
 [149.39845476  14.59568533  36.25651957]]
[[397.92584824 380.00642511 231.55120535]
 [373.07943951  86.1190312  265.95306593]]
[[178.18103429 248.53358351 301.065925  ]
 [ 19.12577873 202.50496303  75.72101753]]
[[ 25.46929431  97.24659662 129.9357081 ]
 [140.11695507 358.84071749 329.67956395]]
[[357.79801259 329.68494209  70.08318912]
 [172.85070209 123.19291884 116.44780403]]
[[168.15132465 270.50131519 376.88988912]
 [316.26564501 121.26315297  31.53925508]]
[[184.34908977 227.61526906 211.14568924]
 [144.41095535 281.33587293 319.951931  ]]
[[312.62532158  39.15797578  17.54843161]
 [111.23804856 386.4230

[[370.44600255 105.00717746 131.60298144]
 [219.21701209 373.32996402 375.42990862]]
[[229.56473436 175.82405955 222.24634911]
 [311.55236343  37.10269753 145.97138975]]
[[323.7524075  131.5384974  147.15058934]
 [238.97928547  10.22463481 257.82138696]]
[[378.87633914 102.31932168 258.38321316]
 [132.76691742 203.4064517  244.57744092]]
[[220.94651392 310.04338548 151.30805804]
 [395.83431148 300.47441543 303.48320673]]
[[287.69086474   6.67794003 366.59255078]
 [ 69.41192421 314.24331467 116.01962544]]
[[264.76792758  51.55580789 373.98623223]
 [167.33085462 381.33674484 338.67800015]]
[[294.81104832 353.84640041  92.8821645 ]
 [ 92.83940044 286.34243253  63.98975333]]
[[379.16800908 298.63272672 312.56494759]
 [160.83947441  82.49156613 145.12334661]]
[[ 68.88750006  44.0166589  149.80104979]
 [ 22.23538124 276.58904792 257.48317806]]
[[245.9572092   89.85977333 335.75485415]
 [278.46107648 301.62021273 265.36737261]]
[[151.65568018 296.34339885 317.05301538]
 [144.42740823 238.7671

[[380.22203878 334.53808951 104.98705105]
 [350.607272   139.76705922   3.404946  ]]
[[219.19665746 318.54794254  73.34105951]
 [328.95802706  77.9912443  309.47904107]]
[[182.52061768 112.43905682 325.35265404]
 [377.32933943  60.54487254 157.93175707]]
[[353.21678061 149.7182921   88.86751147]
 [166.73445706 361.5478457  329.60054983]]
[[355.98701967  13.42052139 224.25860249]
 [322.3527611  285.10555251  40.33001635]]
[[306.86450353 331.0861587  308.33220349]
 [262.7771004   69.78947136 229.68655903]]
[[390.05366321 286.41247729 128.68282579]
 [266.73856284  61.10876804  16.55880109]]
[[262.28674629  39.18368466  38.63190559]
 [371.16245099  30.82338724 178.18150005]]
[[190.22396868 244.41782323  63.10183688]
 [ 39.85983934 372.99324907 358.81481471]]
[[183.71186351  53.64395954 263.68720597]
 [ 43.00319766 306.50243111  19.88791031]]
[[260.53861094   9.67943284 124.13417269]
 [344.1823124  378.15716464  44.81164132]]
[[172.89782921 168.83685352 241.39407817]
 [199.75764114  93.7783

[[123.52622811 270.18407305 194.03556767]
 [314.85734601 249.16206365 332.83747628]]
[[ 71.30864495  83.81188093 163.74496726]
 [ 27.67109938  88.44992433 179.87873774]]
[[386.10113711 313.67991959 285.22198516]
 [ 80.21687765 345.54244186 330.17773882]]
[[ 17.61862251 243.4325028  176.42913237]
 [393.09138098  20.24451036  39.34753417]]
[[165.54622624 235.71038045  41.76909311]
 [242.14158131 183.51253208  54.51149796]]
[[220.095806   222.81253347  53.46374817]
 [213.41664114 326.29142086 399.85311046]]
[[157.07404724 202.63229034 363.39692268]
 [179.99775621 224.02719994 324.56664113]]
[[354.92658719 310.47724645  63.71114373]
 [278.45876765 123.07959112 332.53901705]]
[[ 45.80486829 290.64087722  60.18707733]
 [302.40953299 335.03899436  11.57601423]]
[[279.60974947  23.75833045 251.75496741]
 [ 28.44106824 287.51688589  45.80577335]]
[[170.43535405  59.09248624 386.9122398 ]
 [263.84040454 376.17411595 147.6161278 ]]
[[ 98.07785198 337.13881155  85.26361023]
 [216.77224141 355.6510

[[ 89.75052552 241.67452784 106.81912916]
 [197.27589882 340.80061699 387.39976197]]
[[ 41.15249849 127.950925   364.00733748]
 [341.150279   172.80150055 172.98988837]]
[[118.03613661  23.06542983 230.44691321]
 [ 90.86704473  45.31658084 240.16311158]]
[[101.94742768 305.67027509 328.48685702]
 [120.01623907 246.5697981   21.41639141]]
[[334.73052306 336.43128852   4.96140569]
 [322.82337283 289.54744741 129.81587251]]
[[ 87.14220753 187.93151182 374.48626491]
 [111.41951069 143.20174154 290.52893263]]
[[ 91.73912982 281.98248055 167.46510261]
 [379.08154679 249.80816369 242.38049722]]
[[349.86995921  19.0957912  290.32383723]
 [ 29.82672902 103.53102849 380.27458147]]
[[373.41238406 200.42451112   5.14269561]
 [ 56.35439403 248.91174156 208.24615331]]
[[311.37365817 245.22502752 222.96117385]
 [239.03116979 116.31820347 115.11335121]]
[[235.41360379 312.83801319  12.72520317]
 [ 65.19853943  35.26463817 375.05118701]]
[[196.15071996  84.17006243 298.62390471]
 [194.77682203 273.1799

[[ 32.78976819 322.36630507 368.62054838]
 [272.00177208 303.93966591  93.41883519]]
[[377.73970637 387.42344976  43.27527326]
 [127.85639839 158.44315373  56.91519705]]
[[318.46999841 318.17670659  35.88202668]
 [276.01050221 304.66340015 375.26415688]]
[[160.72999602  78.04421995 374.48498071]
 [192.45251376 112.13798739 118.37665619]]
[[ 96.63948817 398.55521485 132.89547128]
 [ 25.23976924  31.50780873 157.09668707]]
[[343.87620014  15.65091425 374.70702801]
 [254.42107849  17.23605691  99.33663505]]
[[355.02690084  77.62338742 122.7341286 ]
 [ 90.90894362  21.87597544 385.64218756]]
[[138.97411715 378.97590763 273.37686762]
 [183.60294206 310.21444176 298.85555203]]
[[356.61201324 101.99901388 321.73253174]
 [110.59959382  64.91453253 293.60676165]]
[[303.91240793 246.5760042   64.31170719]
 [129.00060752  85.30578438 184.29690639]]
[[181.06393668 195.04341654 331.47929583]
 [224.91935162  74.83247741 259.63959728]]
[[ 80.95939983 289.90117891 153.34343351]
 [240.26675284 242.0586

[[322.87571647 361.72383991 355.15945963]
 [225.59125397 316.8690366  263.81858134]]
[[ 66.0456486  279.91157766 314.33648315]
 [ 73.79469047 191.9952925  299.25799315]]
[[ 50.71798864 182.72116981  16.80016797]
 [348.51234956 293.53341476 175.8312183 ]]
[[169.82120616 131.95472947 262.08536419]
 [115.92587973 182.3215106  193.42284356]]
[[ 39.73721581 388.07716156   1.18530855]
 [292.14228545 259.37157327 277.32985777]]
[[332.13999169   3.91903632 216.00194146]
 [189.04388733 393.38957628 399.27937623]]
[[252.42935481 332.00127517  16.18813888]
 [  8.75499543 298.28829537  10.90783512]]
[[338.32387588 147.6551919  234.37752603]
 [394.56738069 396.26251888 176.58392273]]
[[110.81986278 268.09286243 277.15082032]
 [229.62977817 252.93052481 148.91000387]]
[[398.23213701 294.80262779 201.81190223]
 [154.3592857  339.46635138 327.19977748]]
[[385.71004983  42.68158346 381.8624459 ]
 [ 50.96045271 288.14188076 348.80944475]]
[[ 19.95633408 124.14489196  39.54602129]
 [ 29.41794601  54.0723

[[317.60567989 299.65782107 241.05833657]
 [ 26.96875877 356.79557334 253.73596257]]
[[324.96928881   1.29306919 268.78528124]
 [111.51140907 300.37422434  64.41105483]]
[[217.22461413 201.87529947 120.53704466]
 [305.59779092 323.27535796 161.24224602]]
[[124.3344389  218.45007711   1.26080456]
 [ 68.55084822 203.89046758 124.68556265]]
[[  1.06666373  38.48770587 126.28207901]
 [163.87416643  72.52499666 132.75509173]]
[[397.61672505 250.70701261 312.53413792]
 [179.93294547 264.60092402  58.17157268]]
[[ 18.09627548 325.29758053  28.90769336]
 [206.70631598 398.75146843 298.6231293 ]]
[[214.52306513 254.2763706  297.23708764]
 [179.88955891 356.70680402 127.50388451]]
[[277.71854156 147.63103424  15.83640611]
 [287.29131463 399.71870409 338.50388752]]
[[ 77.52251814 126.09041845 267.89761182]
 [ 88.62678618   0.57048568  61.23892284]]
[[ 10.20019917 264.26372293 114.7217408 ]
 [ 48.85175084 356.57262039 192.90818503]]
[[371.62017673  13.74632115 320.99519045]
 [ 87.46124771 107.6368

[[ 97.26049445 236.91125669 174.76157377]
 [161.04791315 349.40633259 283.35951285]]
[[388.75288469 387.85540596  59.69311669]
 [262.74511736  48.4665769  248.87776877]]
[[303.04242833  59.55556584  70.69312357]
 [381.37689644 386.09820476 247.37849041]]
[[130.40297395 215.71688896 348.80139593]
 [319.22026315  76.12244867 222.35883256]]
[[378.41487531  93.63263647 186.29956023]
 [213.07577398 211.5846958  120.81930709]]
[[272.30067459 160.19681747 361.84934403]
 [317.29936762  66.35109188 198.03809832]]
[[232.41085806 248.71353821 108.08689614]
 [ 60.5313251  367.36168116 262.57087819]]
[[305.18047885 324.64120464 193.39709322]
 [172.23597355 386.59598213 246.0307476 ]]
[[232.54611453 235.05837408 240.34454333]
 [193.14026454 108.6941423   35.23233042]]
[[ 55.71654323 306.18299482 181.43377328]
 [374.38128312  81.66892488  76.04846586]]
[[167.79405091 199.18795401 333.5191764 ]
 [374.60336135 266.96324462 245.40869153]]
[[185.62096685 365.75164784 378.39091663]
 [209.24038981 250.6243

[[ 37.73163112 101.65849236  26.37858377]
 [230.15030549  90.16528383 314.34984874]]
[[229.5772898  290.03678137 193.54434199]
 [212.63848165 119.71521851  26.96352716]]
[[169.706132   201.22134548 370.15065121]
 [154.91199449 146.61120368  66.68126544]]
[[392.14176734 173.92837148 328.99922413]
 [170.83304017 196.25688059 266.7988002 ]]
[[235.43811557 221.23040399  96.25290404]
 [ 63.78350173 168.49806842  99.4423256 ]]
[[150.3960196   75.34882505 144.03227037]
 [349.81066629  55.60733809 177.93926402]]
[[ 25.78738258 346.31403971 142.5831093 ]
 [278.01104112 260.48975972  43.54986485]]
[[218.0522939  262.45041499 284.81031444]
 [142.29614222 378.10014894 251.91538521]]
[[263.88355483 116.79519121 237.28524723]
 [297.42273399 364.59527974 162.56974344]]
[[ 84.34041872  82.83773514 181.33816481]
 [395.01472996   3.14517801 325.25523403]]
[[242.12215689 144.42731625 198.09188438]
 [362.36300764 381.79212353 171.65219865]]
[[383.22392523 144.98543704 286.1356903 ]
 [119.63766205 287.0779

[[111.47901806  65.44896166 258.87463378]
 [212.33502019 328.41754889 149.99458863]]
[[ 26.65184766 375.06045652  45.40376139]
 [342.8392696    9.20514539 389.85387799]]
[[194.84304513 233.3307574  271.53705231]
 [162.58497292  92.68285657 296.23880092]]
[[328.64466369  98.84761502 296.44111121]
 [129.88558687 373.15748619  88.36106376]]
[[ 55.14301296  35.80116432 176.02845617]
 [147.61188236 172.73934244  69.58887923]]
[[236.91959443 298.66395232 172.17604195]
 [395.58744206 107.60293736  23.67084678]]
[[3.39529859e+02 1.64444827e+02 3.01532870e+02]
 [2.69352404e-01 2.98774531e+01 1.18878851e+01]]
[[322.96760176 265.34904977 187.04238746]
 [ 64.57975269  29.35874959  13.54901128]]
[[283.54914009  65.64532323 302.93053674]
 [272.38605602 179.16107781 252.3419993 ]]
[[273.88808645 273.02706475  15.26182185]
 [121.93610572   1.70791981 255.78577057]]
[[211.56403437 194.53437835  51.68112314]
 [ 17.02090871 177.83927686 277.3735932 ]]
[[ 18.6297629    9.34066288  72.19928721]
 [360.71631

[[ 29.43193919 177.83317929 357.90384991]
 [209.67378671 242.99959574 245.20429843]]
[[259.74450288 215.37785944 110.52534565]
 [247.16523032 249.31645517 307.16473315]]
[[292.74207762 255.59682166 238.3114926 ]
 [201.44748549 121.07260688 282.91132026]]
[[359.23859943  86.36550593  34.19560728]
 [276.71479852 308.47696513 150.41826265]]
[[ 70.89747003 299.07759915 202.66141009]
 [302.07325433 126.22580939 298.95709131]]
[[  3.85300192 379.40053275 223.53889234]
 [241.83716983 153.91797194 100.98100176]]
[[102.68756052  29.5399753   79.92226755]
 [247.64901232 233.02173703 253.80224293]]
[[240.85316993 342.90497107 185.37118114]
 [128.9374671  263.95822983 136.66273942]]
[[ 40.53728798 251.49236278 188.82916953]
 [272.21366358 148.40134418 302.08092355]]
[[398.39303701  77.00578859 241.30616884]
 [236.20399757  33.49945287 113.60493241]]
[[253.25330816 193.25428849 363.86200847]
 [301.65525314 232.62011578 331.47678266]]
[[106.95866467 165.30836807   1.80688391]
 [311.2767644  343.2626

[[111.29902797  51.47691792 219.32857117]
 [184.10912954 313.35194844 292.80749405]]
[[297.60616575 299.79651112  13.97579608]
 [321.76810819  34.45646877  65.47522336]]
[[134.95294974 389.9454498   70.93919597]
 [118.39785032 277.4071172  332.81642128]]
[[136.5653705  356.35623963 196.75704129]
 [146.87117938 158.0079836  397.21664419]]
[[355.82101538 304.04263494  19.13497852]
 [362.17392813 310.07480085 283.82456447]]
[[ 65.70803763 146.00304452 292.47746717]
 [ 77.62759116 386.3537712  293.74580211]]
[[325.88170096   9.04146866 310.3268663 ]
 [129.68812183 112.99266723 299.35218388]]
[[386.98284818 198.22316741 131.73085319]
 [342.50936207 196.2718163  315.39384338]]
[[143.16487878 309.53169149 200.25167164]
 [101.03309377  43.44015569 239.28162984]]
[[270.49312894 283.55387394 301.79825389]
 [202.47201994 368.42735842 231.39585445]]
[[241.03998042  81.14620906 231.57766981]
 [350.03567923 396.84735816 365.54440967]]
[[363.3606486  154.09155361 395.79140483]
 [367.22247194 399.3134

[[224.47441317 306.37948414 370.76748682]
 [357.5170938  105.86101902 306.2049043 ]]
[[ 22.35913356 347.50304573 221.80698414]
 [253.77774975 385.07860747 174.44531767]]
[[180.85817907 197.97851981 299.96731868]
 [116.20668721 128.58586839  28.81801193]]
[[369.44121778 230.97796109 178.10137393]
 [ 56.35512825 398.48292224 236.7418174 ]]
[[ 49.37618422 299.24894695 391.14384119]
 [264.96538951 240.7589716  360.58026592]]
[[376.17248853  35.72592756 259.90691284]
 [147.27113029 397.93637055 182.37932816]]
[[233.45746053 186.09379759 138.50540418]
 [ 72.26141275 383.93192913 237.7339766 ]]
[[ 92.72606237 139.71459925 100.75389117]
 [296.975424   215.3848726  218.65476721]]
[[305.03279747  47.95560254   2.04823276]
 [222.69668654 363.81708759 187.99521264]]
[[347.17757947  88.62439771 399.05545095]
 [119.42584427 362.01065612 130.2862938 ]]
[[112.2308487  372.34051378 104.75750902]
 [193.66037101 157.6414579   27.75392567]]
[[391.10895346 208.97755813 174.26604494]
 [294.88334369 361.2616

[[118.27375847 397.80680782 181.70174177]
 [191.97005139 170.67055703  67.10730621]]
[[101.14496303 379.96054351 145.18724104]
 [283.80208572 176.93659152 387.37400805]]
[[226.57564852 149.34091415 239.63341846]
 [ 46.3104852  263.64650096  60.77918338]]
[[207.56052172 175.50671418 126.68698309]
 [236.98436591 304.7333606  367.27218786]]
[[ 82.86054087 204.62220626 170.83139644]
 [ 91.5702999  215.4331123   81.58077964]]
[[341.79940482 241.58967517   9.2775484 ]
 [272.43115927 112.84346087  44.48847512]]
[[130.03160273 384.33352016 208.35586848]
 [118.96723455 188.54112618 208.80271715]]
[[120.5560861  109.58890438 156.81125343]
 [321.74850006 161.98405757 309.12038339]]
[[146.9143966   81.14617352 220.91797739]
 [ 75.59958178 391.41634867 180.23054798]]
[[287.41221764 169.85757573  13.66978443]
 [130.08096447  21.15409153 339.15790124]]
[[159.39577078  24.51850633 121.42303632]
 [ 29.25155415 202.16947503  62.32045857]]
[[289.4999813  366.0265938  243.22720587]
 [ 61.95352272  71.6802

[[270.04206601  45.96185885 246.04274762]
 [326.90181866 333.10479514 281.45985486]]
[[ 11.41486837 359.9483611  320.87797532]
 [342.08406854  18.73399463 279.36927988]]
[[296.31572993 325.05438804 254.27123094]
 [118.59241638 278.22580158  82.52742866]]
[[3.36053006e+02 3.13204846e-01 3.98134509e+02]
 [3.86376758e+02 1.34719647e+02 2.75267748e+01]]
[[262.66960922 370.05547494 379.89488008]
 [255.01679889 268.63143379 304.66665248]]
[[390.52358442  90.57743227  30.27336091]
 [171.53611286 316.23860594 320.08629137]]
[[ 25.7292215  387.41246088 152.60346334]
 [367.03307983 287.4634599  166.71636497]]
[[109.02790483 128.79552649 103.54276366]
 [ 68.2622625  366.58027553 313.35645804]]
[[253.04930074 105.83719789 127.63869463]
 [322.38569077 171.77802581 370.1796276 ]]
[[ 75.83228447 245.57530736  94.71874572]
 [ 56.89073908  75.23722142  29.17809126]]
[[106.70594947 144.51713088 320.05274482]
 [166.97538068   2.38456529 220.6537812 ]]
[[142.30387233 196.56098001 316.3020929 ]
 [112.70512

[[210.40070708  36.51684007 394.68091591]
 [132.62253195 179.19107417 300.41830776]]
[[396.52110066 257.94755416 342.19770473]
 [275.45766705 293.97808577 280.81077611]]
[[134.85685311 252.71150049 123.97187898]
 [102.67269656 335.85997912 326.00989139]]
[[355.77656831  65.12032296 205.36093564]
 [266.69849226  25.26059902 119.92609044]]
[[365.68604072 279.19268192 182.31161809]
 [301.82008613 359.47032245  70.47994484]]
[[276.53633453 311.99300004 169.71223418]
 [ 62.36041396 373.78186312 146.77920716]]
[[205.27993954 254.52480156 345.06738959]
 [  9.01817616 257.47401662 157.2315193 ]]
[[291.90737761 214.48023107 376.58903881]
 [159.39230563 259.74829076 130.9238382 ]]
[[360.51333533 118.69978041 364.64797216]
 [329.32862745 187.86776944  70.15461922]]
[[351.73051669  80.1971286  120.40348003]
 [252.63845288 126.42401371 146.0535513 ]]
[[ 13.57973183 391.53965456 242.64643963]
 [321.75586411  37.49173595  70.75434369]]
[[143.86247403 191.70002561  71.01022005]
 [286.56213583 353.5662

[[156.16322383  64.31310605 328.1982984 ]
 [207.42122222 331.29488182 277.67383603]]
[[186.27260227 261.63557949  47.54023611]
 [234.04278527  16.59956269 322.19187358]]
[[377.0801866   36.66917243 313.79531449]
 [132.29681403  96.92515028 275.22304939]]
[[171.07957566 186.64111441 163.22592446]
 [146.88197605 270.95667829 204.2346422 ]]
[[257.41079619  71.55833754  98.02233706]
 [336.37056701 131.95144607  14.72795456]]
[[195.03936286 103.0104497  133.13764102]
 [226.10428863  89.31378477 136.91113346]]
[[263.66663976 374.70315648 187.95191641]
 [383.23770762 271.92024614 212.93323473]]
[[180.28585986 246.79958261 155.4991461 ]
 [  6.2320292  218.56314301 119.51940819]]
[[ 83.76757372  56.73274305 119.16130458]
 [ 27.87703177 142.13264739 181.94244527]]
[[208.77262077 223.00534732 171.00876253]
 [277.47969222 327.28591467  72.91804362]]
[[303.49219521 225.2043309  385.66027728]
 [260.37130628 215.85865613 377.61510392]]
[[ 71.69820125 391.53910156 233.25663172]
 [102.22565706 204.8301

[[130.68541242 242.24985381 200.76198726]
 [102.51809718  38.67455047 269.52447783]]
[[231.6512773  381.24290028  19.75795975]
 [313.57771197 231.91258599  71.53765303]]
[[188.66481194  40.33797707  17.47810511]
 [144.50494197   2.51425616 141.16133167]]
[[ 89.59739507 363.96369837 389.05069103]
 [ 55.88852335 330.76671407 319.11729084]]
[[163.40746411  66.28772334 243.19673596]
 [ 59.84161284 314.14242905 253.10053145]]
[[ 43.36324797  10.67353129 144.03319838]
 [181.30672278 309.77433079  31.3283635 ]]
[[127.99439832 157.29560859 204.28515218]
 [128.49510378 331.08711224 141.49958448]]
[[114.57444993 222.96908122  30.6862251 ]
 [313.79428104  58.37822782  70.38980079]]
[[156.54697031  53.56859033  70.4976353 ]
 [364.76005244  91.99089244 249.0757283 ]]
[[ 93.57696813 341.26533422 360.35369666]
 [283.11333294  33.02474817 254.86453122]]
[[ 31.58103202 176.41794572 121.03603016]
 [ 36.2272721  162.19509588 171.53078771]]
[[199.84956062 199.96138469  91.78459523]
 [353.2883524  324.3793

[[297.56262529 326.04655119 103.45519325]
 [278.72104421 261.41924646 219.45701938]]
[[200.30854177 393.13504917  83.94288835]
 [226.46649684 166.56871336  95.54727359]]
[[300.72549641 146.50464601  82.20675171]
 [192.52488216 149.16078457 327.34085709]]
[[285.49762584 131.04688298  93.25652602]
 [ 78.00421939  96.76548194  11.88819422]]
[[352.61631787 341.01310786 370.63440852]
 [100.03461792  39.86241108 167.78516981]]
[[158.1288401   14.19528384 225.4051087 ]
 [162.49488274 324.31202842 203.57402261]]
[[ 24.4285811  160.42038598 187.42441581]
 [228.54761508 218.38975178 336.61198262]]
[[197.9946877    9.68655014 246.74255517]
 [392.28888498 211.04696348 384.86119466]]
[[252.02014163  67.27959968  52.02961583]
 [212.17130337 371.29647529 231.00925359]]
[[215.92995525 317.27815724 286.73005594]
 [218.82021103  30.78491254 193.85108569]]
[[156.91201003  76.75277614 288.38640714]
 [152.53019304 204.05339263 198.36046386]]
[[272.47830589  36.95218218 274.54365435]
 [258.53159397 121.8682

[[370.96050549 290.95797652 346.23042766]
 [ 25.09734209 360.91858339 202.1742182 ]]
[[142.05881968 114.38397183  89.50829963]
 [ 37.39867286 381.81982358 207.31113504]]
[[128.81081788 304.44861102 391.94713853]
 [364.95926368  95.77011063  52.63735554]]
[[280.60199034  72.05254527 222.84567164]
 [ 39.97282511  83.43183522 335.06618224]]
[[ 25.82790117 182.24877119 352.34320199]
 [ 80.26929833 271.55923105  72.75261446]]
[[198.78603881  40.91337069  63.34563119]
 [316.38039514 312.62007971 399.10470535]]
[[  2.34597691 368.34016614 193.31986796]
 [186.60867955 169.41114159 139.47294037]]
[[376.79964542 326.58082079 143.2635374 ]
 [182.42296967 341.97632447 312.02074778]]
[[196.91805111 100.826414   344.61310081]
 [109.90924242 325.22625972 145.35202018]]
[[283.69963086 194.59982859 143.12472765]
 [167.06830221 386.37295831 243.61703547]]
[[303.51279793 206.08842992 344.75701651]
 [144.01996532 284.33176491 274.44343843]]
[[393.53511314  31.46119267 157.77051295]
 [183.64144093 283.1293

[[295.21951011 163.31840177 205.97654423]
 [243.89150907 358.06836657 367.91428778]]
[[352.06904355  37.71810842 386.934188  ]
 [ 91.92465635 318.83349082 277.59292048]]
[[254.68602207  40.47984034 224.50977023]
 [289.25245459 116.77110129 361.92619076]]
[[ 19.91605739  20.4356581  378.75905788]
 [344.1804234  173.10913454 147.04594113]]
[[243.01045788 181.18704585 249.55147137]
 [373.70156279 366.967556   187.41903487]]
[[377.7921323   35.66797776 372.07489469]
 [158.99717061 192.71087275  18.83485826]]
[[195.48626751 112.74951772 269.45649542]
 [100.30135491 347.24504717 318.51572693]]
[[255.19650445 352.7690368  299.14941254]
 [ 26.51366133 267.5771742   26.78108866]]
[[ 25.08276058  86.42744124 315.13366382]
 [ 26.46029194 133.27883503 344.16355273]]
[[ 85.54577967 328.82319115 181.05970014]
 [379.4505383  117.75645956 282.30835679]]
[[170.52645305  49.96375748 147.62770398]
 [ 72.40434944 307.9884973  261.24278479]]
[[304.549132   173.48816142  10.19247984]
 [ 30.50129798 157.8073

[[117.63318727 240.7194062   94.04196742]
 [ 20.93759828 328.27714877 335.97933136]]
[[110.68140732 386.59884294  21.75228077]
 [258.81740588 325.45025202 208.64884429]]
[[225.31825006 210.81080309 275.1091026 ]
 [ 49.61566106 349.28895621 329.13649793]]
[[119.49709868 217.42475619 311.41008089]
 [225.79265956 240.04870947  52.6816134 ]]
[[108.37099504 297.61356146 372.83067129]
 [135.69253265 180.88743357 121.59350804]]
[[ 10.25930179 364.15742529  27.47452545]
 [ 76.60951368 259.52962064  69.54093477]]
[[249.89152494 227.3942302  267.47223806]
 [309.87279237 345.8195143  209.87805881]]
[[311.74488759 179.31001386 153.29440293]
 [272.79240139 399.56723769 331.29825995]]
[[166.82697646  59.32675702 227.01523799]
 [387.50903159 310.65795066 334.29095704]]
[[120.59460922 138.43957674 173.17172012]
 [ 60.64544929 138.40362434  17.08025969]]
[[297.64101023 251.97453968  57.206121  ]
 [112.68014395   1.27405292 266.40129376]]
[[174.07797336 194.63598313 283.32305361]
 [313.4161718  117.7070

[[252.89378025 278.59908845 369.0970232 ]
 [ 85.21471221  63.41077658 240.71213641]]
[[228.30928063 292.86532258 326.05595644]
 [253.30782555  46.93831776 266.61695099]]
[[  4.8016635  321.73829018 166.48990886]
 [ 52.678706   114.12558438 223.66163507]]
[[  0.62772528 136.6760847    9.48550342]
 [233.21602777  43.58857354  90.00241927]]
[[282.14268452 277.48796572 371.21804518]
 [381.57450094 266.03498029 276.12819176]]
[[384.91795163 123.37089283 217.88762456]
 [ 20.81385207  85.20160654 346.94121183]]
[[131.02453702 352.37575868 208.01327422]
 [302.23871109 321.5245828  253.64043143]]
[[ 27.54876756 227.83282799 179.18875757]
 [135.42405263  70.05483981 259.51139443]]
[[201.25133172 269.65253424  39.5156075 ]
 [264.85560703 180.23817327 292.5940844 ]]
[[158.62271658  34.58939073  69.8466843 ]
 [ 43.15191362 134.75080237 381.65874588]]
[[362.69329932 242.56344701 264.10310671]
 [372.08042612 333.90300878 245.58742257]]
[[376.68825631 257.2560427  347.50176441]
 [399.32399408 127.4245

[[108.12981113  57.46805709 183.43629675]
 [301.89482393  49.00583663  44.16014104]]
[[249.48127971 302.88788534 256.92657614]
 [318.09000641 200.93884043 313.68198639]]
[[191.73542004   5.09755263 166.38005745]
 [ 69.48066785 345.01746738 387.90283182]]
[[200.73026429 273.9907694  207.9493466 ]
 [190.28385263 275.85923503 160.36960076]]
[[ 17.75126987  86.95486358 137.41013955]
 [228.3274194  139.97000196  29.1386146 ]]
[[271.09410643 284.92437828 259.15169986]
 [241.93009769 287.16489174 392.25805039]]
[[200.89516209 392.84733186 165.12664543]
 [132.23400915 333.61905544  76.76308198]]
[[121.88059321 330.13013143 106.75380789]
 [271.06198895  13.67191334  64.93127338]]
[[342.91218274 204.35184093 182.03909993]
 [203.20807624 132.39761027  73.58629085]]
[[ 45.01855602 318.81081792  99.93919044]
 [314.82907855 384.48376477 154.5012157 ]]
[[139.97567077  49.00230248  21.52006752]
 [368.56296288  37.11274065 377.02338878]]
[[122.34816118  47.40948993 340.07794679]
 [214.49101776 279.4960

[[ 59.23890618 268.22013371 253.67362069]
 [ 55.97546836 341.5415796  339.63559875]]
[[274.36464512 168.06326763 111.60035741]
 [332.37506658  18.70902642 103.63657188]]
[[241.20888591  38.60548213 345.10181007]
 [262.74577747 137.26784031 212.93856784]]
[[220.30816953 246.17810643  22.1747182 ]
 [192.52116819 395.01490451 238.80204154]]
[[320.04063156 117.84233596  76.15145046]
 [372.38172382 366.43701456 115.46871875]]
[[ 29.6141987  119.38784652 387.86999124]
 [378.9132292   62.03016605 276.24589052]]
[[ 13.57354012 398.18565342 228.67988115]
 [213.37863047 103.86472273 315.43969072]]
[[192.10234903  56.55908478 164.44336901]
 [334.65868666  18.75238058 258.27514174]]
[[ 47.53656074 210.75041076  75.2872354 ]
 [393.04694185 332.43574814 271.56823327]]
[[101.58373593 189.49535589  50.74188555]
 [153.54554646 156.3933911  281.46604316]]
[[211.90396133 171.46670777 253.13130356]
 [320.0533358  271.18774262 345.94819286]]
[[241.20293348 215.79606643 332.48329477]
 [102.87831909 257.2153

[[200.20655171 383.77904044 374.61152863]
 [104.77928774  71.59690215 338.18137276]]
[[250.60648076 243.73666565  21.9200013 ]
 [107.03585891 316.17150318 120.82290078]]
[[127.39251381  71.76354705  92.61726927]
 [348.49069841 387.15593636 347.80347825]]
[[382.94583078 281.47650051  18.38436868]
 [103.0559422  173.36143029 271.44999478]]
[[356.97041915 292.85520871 393.93391812]
 [197.40965456 331.22498444 246.36809121]]
[[149.2368397  361.37009915 247.86723738]
 [ 70.44088429 341.17041049 322.60156601]]
[[192.14104692 245.25900272 126.75287097]
 [ 42.53193977  71.86030241 351.52135747]]
[[105.03994714 373.58133744 148.07032791]
 [392.02018225  94.96330516 128.58782501]]
[[166.17164095  21.05360412 269.33115498]
 [244.45477123  56.82786957  40.11116949]]
[[185.37205689 111.12756198 177.67829143]
 [358.65833827  14.2339917  380.64517585]]
[[ 46.38284404  15.2308228  338.83683707]
 [205.03543047 379.89506047 140.17383507]]
[[  1.60580157 286.66594453 399.42914992]
 [ 23.16103641  76.6227

[[275.2389003   97.5770526  389.46336729]
 [364.50793003 160.32787929 130.28371315]]
[[ 69.06516466 128.70518764 134.23947585]
 [119.91677825  55.54238531 319.77670637]]
[[ 65.59607019  77.43257901 109.19361688]
 [391.94895495 277.78344472 212.92958491]]
[[392.70280456 291.01103251  16.38865639]
 [276.40890752 263.8470835   36.37280997]]
[[ 18.98841748 353.01497237 149.7698316 ]
 [184.29384788 137.42245062 244.36599502]]
[[117.65881058  46.35943856  40.34778221]
 [332.51207161 202.30943616 286.50113789]]
[[396.1490484  190.67993491 183.76791523]
 [279.37714018 285.16916124  66.1681236 ]]
[[130.88822908 162.60863119  80.1851418 ]
 [185.14207073 345.38606988 266.27358678]]
[[ 99.73516752 239.99535392 168.41690707]
 [ 47.21590695 246.93416245 164.57722538]]
[[363.8071342  148.56369497 178.137281  ]
 [211.63913994 121.24678627 339.20227699]]
[[306.82217586 299.5794026  235.10342943]
 [335.87744963 267.37943879  31.68324543]]
[[387.6970918  190.19568916  47.22946833]
 [192.95770543 241.9178

[[349.70956633  32.13591643 276.52100973]
 [327.02973339 319.62280162 360.85061523]]
[[384.79113329 212.07088031  10.68001288]
 [145.65323677  80.70452245  32.21381149]]
[[92.55090001 25.21614426 68.53558215]
 [94.71441182 77.92592863 63.78411947]]
[[147.87866398 284.4265706   99.2009345 ]
 [391.32642371  45.84541546 278.73718288]]
[[243.07635322 142.50968282 171.79527034]
 [170.21281923 321.74933476 347.79609963]]
[[333.84474233  37.11681288 266.53936907]
 [157.64733003 200.13049271 341.33843605]]
[[ 99.71292562  63.02596373 225.56416483]
 [ 70.6308951  199.76819702 346.96301789]]
[[334.73760373 372.93282654 265.606554  ]
 [166.42194406 195.30927328  60.14686814]]
[[ 46.82709486 161.64174067 397.03700231]
 [ 51.73059962 214.84720532 194.38482482]]
[[134.08432002 309.47458993 128.02451985]
 [ 61.58739355  67.4804668    1.10028392]]
[[  6.89946153 245.40999468 390.02554802]
 [198.56038393 279.50333157 150.59676454]]
[[151.84192917 385.4717437  243.00826563]
 [287.72614093  59.88951142 2

[[ 80.57223721  88.71075803  80.64048281]
 [ 25.96402148   6.49553891 319.00378551]]
[[157.20036866 278.33673643  76.18048905]
 [ 90.92299764 326.67395795 319.792621  ]]
[[ 73.7027907  393.04756664 178.12479678]
 [392.20910413  28.86398402 194.54111237]]
[[287.59643432 275.55738815 285.0332715 ]
 [270.32048629  24.96760793 268.80163748]]
[[123.00476673   7.78779308 217.10605651]
 [ 32.9582103  162.2069571  251.8268908 ]]
[[322.13882046 205.75106661  10.59951411]
 [190.67254191  92.34860896 375.9808912 ]]
[[1.30160936e+02 6.94615100e+01 2.43909631e+02]
 [3.14277952e+02 2.90946677e-01 3.77395927e+02]]
[[261.89355259 374.42277305 365.84037651]
 [ 90.52754035 110.96601622 208.80154141]]
[[ 70.86877342 109.94022647 251.19164226]
 [167.72521362 348.15133854 211.83408017]]
[[396.71076426 339.98112618  67.84151735]
 [317.28403421 204.41715536 324.74571917]]
[[106.36645331 399.84563679  73.56227045]
 [ 88.57223816 110.32277126 263.29530322]]
[[ 20.33205145 293.17266289  57.6238064 ]
 [262.79424

[[186.59481971 295.21828227 318.06593627]
 [223.89748058 201.21363668 218.1643209 ]]
[[313.13030104 216.2646572   64.80718847]
 [204.25327776 357.60070699 253.83014141]]
[[243.9171857   32.29343166 165.56835305]
 [317.51817656 306.25906787 136.20927367]]
[[294.4526141  381.19510867 189.00010975]
 [ 12.70440281 241.43432491 381.48285578]]
[[ 48.48085353 342.36739546 276.60861517]
 [213.3735694   87.08344377   7.18101788]]
[[242.78918479 377.14294698 121.33980915]
 [249.01944792 160.99910061 360.62192828]]
[[378.20917566 395.75782287 261.39288067]
 [328.19636539 306.3596812  269.25763449]]
[[185.83809831 293.30524642  98.29389349]
 [240.5293577   26.85504006 325.29961939]]
[[271.83259508 200.39474118  36.29338313]
 [ 69.49649846 371.2338306  327.87306444]]
[[313.36977594 253.42963176  30.8504331 ]
 [201.5073176  221.02714888 397.90327984]]
[[ 66.81544258 325.99471313  47.16782708]
 [123.64732743  91.40773711 349.71132681]]
[[ 57.64031539 195.92067736 346.20323436]
 [154.49063067 280.0405

[[282.53752706  79.56133633  69.18158711]
 [ 48.91906503  15.9552281    9.41564516]]
[[184.17253737  90.88445853  90.69116475]
 [ 22.57245563 111.66005924 210.44070068]]
[[123.191516   115.79912938 160.69471583]
 [247.75208707  31.24013831 139.44926755]]
[[174.52629655 308.07410284 108.66453313]
 [ 17.87962227 218.15257695  50.33747298]]
[[237.09946525  51.70336398 319.45528751]
 [202.66322954  22.78261051  65.42409357]]
[[174.32528889 381.36210138  88.40011635]
 [109.36801995 341.51716643  27.10053851]]
[[149.88235683 162.29164596 370.13692573]
 [ 91.01987272 362.60371021 149.98368979]]
[[323.55569588  16.99315049 102.66295406]
 [285.76303551 361.81130309 291.15908436]]
[[163.23861083 207.32628965 275.19965447]
 [110.09991368 394.30423516 159.49212396]]
[[281.35365706 284.37670792 178.03600626]
 [ 71.8095118   30.83797806   7.50162161]]
[[ 32.4730128  174.28840776  36.28590796]
 [338.19735091  67.8398099   67.3522803 ]]
[[276.68557209 309.03918471 177.88081702]
 [ 81.76099183  90.2587

[[ 79.64741205 254.90041024 213.07369596]
 [380.1438993   69.37439872 366.36557049]]
[[ 83.20841897 362.73255997 381.19797665]
 [310.17222839  24.75094595 186.4900732 ]]
[[221.884351   262.32477496  60.20692414]
 [ 10.1920176  185.35400101 209.0341389 ]]
[[ 87.35720707 364.56327137   5.6410146 ]
 [344.67966735 179.31552424  77.68872331]]
[[ 72.69150822 272.14284893 309.19871354]
 [149.27532806  85.67265481 237.79815651]]
[[ 76.56007819 193.94010168 115.91845395]
 [ 48.68649347 239.65205259 288.46190425]]
[[294.24881286 351.19338922 328.34588099]
 [292.22448139 121.129582   136.65888   ]]
[[ 18.05707356 385.20292441 264.47020108]
 [102.61799976 375.76287181 346.38018569]]
[[ 17.19034587 292.73423591  38.69101883]
 [ 16.93673763 192.74511387 171.84647977]]
[[ 24.59473427 337.08285345 359.31625226]
 [ 66.78909804  13.68862343 112.89203167]]
[[184.79316578 120.06029913  95.62638852]
 [ 78.1386765  243.69616237  79.45577149]]
[[160.81921732 397.45310469  75.97331773]
 [344.41946666 372.5253

[[351.73174447 134.07609598   6.09275909]
 [104.63166926 302.66710487  94.50471331]]
[[320.42414474 130.7000164   88.0577415 ]
 [298.40471167 328.757807   149.98995865]]
[[364.3338764  193.86066404 295.76132695]
 [299.23961112 370.08910049 361.59943369]]
[[338.29955092  43.34251399  56.92929599]
 [252.68520799 363.45273458 380.46633797]]
[[133.21007764   1.12202768  53.02756417]
 [130.01550653 362.07727595 302.92217165]]
[[ 51.53615444 317.42577845  87.68887723]
 [340.50999886 314.25514226 330.65244613]]
[[339.17959421 366.96279235 130.85819285]
 [338.9006164  169.22002655 388.39049453]]
[[ 38.13116337  33.29597741  11.04376901]
 [166.76690549   0.84467828 196.12340487]]
[[310.46219126  69.75277327 114.85857038]
 [360.96886516  48.51473107 255.35980071]]
[[146.74833462  53.07633108  17.74498562]
 [331.59024709  32.54428811 315.44964682]]
[[334.75366893 103.91562069  37.52443746]
 [ 93.63363671 143.51930812 284.63304886]]
[[294.33164728 207.98504905 356.40789281]
 [392.20261634 372.4876

[[136.09309498 207.63583608 151.70763826]
 [173.58848354 339.82900127 346.41866333]]
[[376.39622991 206.85279966  29.35551004]
 [275.90773005 386.58658084 218.57269875]]
[[164.21374053 289.65977295 170.9781221 ]
 [ 11.78077181 365.02294666  70.90478278]]
[[175.60234792 256.24841018 166.54395231]
 [  6.10659213 135.9278991  328.97529052]]
[[252.93686252 303.84303858  77.143204  ]
 [ 16.87895293 163.81404163 270.25009227]]
[[189.047897   383.04435288 202.71680253]
 [158.82129394  88.24467864 200.01384616]]
[[307.32283969 344.49223541 225.15332834]
 [303.32925645 155.14824961 250.70322285]]
[[308.2717454  202.31576539  69.60294725]
 [ 42.45693687 305.44355371 378.86660622]]
[[ 13.54121116 191.42452832 356.52902799]
 [216.11896129 115.12300639 271.96236434]]
[[ 71.81066955 386.59854355 338.6970027 ]
 [  0.91652371 179.97579835 290.29428208]]
[[  7.40427779 370.83657364 110.45401379]
 [305.7552436  352.49200801   7.35441259]]
[[129.72774368  63.21422585 289.48804201]
 [277.38649387 152.7761

[[245.35607276 107.32062111 338.07335995]
 [168.90749087 138.76818833 120.38011871]]
[[154.65828028  54.11756963  65.71139037]
 [391.03649808 381.25078549  26.36415684]]
[[313.32661861 230.71184814  33.46359103]
 [115.00213653 362.59443665 126.81905875]]
[[344.75936575 301.8680271  398.10748129]
 [162.47756898   5.40380863 351.28414465]]
[[ 92.07946357 229.80997101 276.01070075]
 [190.46008347 357.26885597  36.58706884]]
[[ 12.30189949 352.88289485  65.99846196]
 [307.83793392 229.20615015 107.69063778]]
[[306.24198124 288.3820551   42.88659223]
 [287.82674104 298.50077835 373.03555389]]
[[231.30823153   1.50680805 131.76267192]
 [281.31824958 152.78413074 311.91941633]]
[[293.73906608 132.82077023 347.38141239]
 [356.97547113 395.48417068 351.60542341]]
[[120.58635042 380.45888983 262.61045233]
 [ 42.14693063 372.6291705  186.88815367]]
[[141.22070467  61.06831149 316.84792033]
 [243.82141356 153.70245102 224.72734206]]
[[384.99024122  77.72280671 295.20031491]
 [ 60.17356127 358.6057

# Partition dataset

In [25]:
# Imports

import os
import re
from shutil import copyfile
import argparse
import math
import random

# Partition images

def partition_images(source, dest, ratio=0.1, copy_xml=True):
    copy_xml = True
    source = source
    dest = dest
    train_dir = os.path.join(dest, 'train')
    test_dir = os.path.join(dest, 'test')

    if not os.path.exists(train_dir):
        os.makedirs(train_dir)
    if not os.path.exists(test_dir):
        os.makedirs(test_dir)

    images = [f for f in os.listdir(source)
              if re.search(r'([a-zA-Z0-9\s_\\.\-\(\):])+(.jpg|.jpeg|.png)$', f)]

    num_images = len(images)
    num_test_images = math.ceil(ratio*num_images)

    for i in range(num_test_images):
        idx = random.randint(0, len(images)-1)
        filename = images[idx]
        copyfile(os.path.join(source, filename),
                 os.path.join(test_dir, filename))
        if copy_xml:
            xml_filename = os.path.splitext(filename)[0]+'.xml'
            copyfile(os.path.join(source, xml_filename),
                     os.path.join(test_dir,xml_filename))
        images.remove(images[idx])

    for filename in images:
        copyfile(os.path.join(source, filename),
                 os.path.join(train_dir, filename))
        if copy_xml:
            xml_filename = os.path.splitext(filename)[0]+'.xml'
            copyfile(os.path.join(source, xml_filename),
                     os.path.join(train_dir, xml_filename))

partition_images("./workspace/mobile/images/multi_lines/imgs", "./workspace/mobile/images/multi_lines")

# XML to CSV

In [26]:
import os
import glob
import pandas as pd
import io
import xml.etree.ElementTree as ET

def xml_to_csv2(path):
    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        #print(root.findall('_object'))
        for member in root.findall('_object'):
            # if no line
            if(not member[2]):
                value = (member[0].text,
                     int(float(root.find('size')[0].text)),
                     int(float(root.find('size')[1].text)),
                     str(0),
                     str(0),
                     str(0),
                     str(0),
                     str(0),
                     str(0),
                     str(0),
                     str(0)
                     )
                
                xml_list.append(value)
            else:
                for i,j in enumerate(member[2]):
                    value = (member[0].text,
                         int(float(root.find('size')[0].text)),
                         int(float(root.find('size')[1].text)),
                         member[2][i].text,
                         str(1),
                         float(member[5][i][0].text),
                         float(member[5][i][1].text),
                         float(member[5][i][2].text),
                         float(member[5][i][3].text),
                         float(member[5][i][4].text),
                         float(member[5][i][5].text)
                         )
                    
                    xml_list.append(value)
    column_name = ['filename', 'width', 'height', 'length', 
                   'class', 'x_0', 'x_1', 'x_2', 'y_0', 'y_1', 'y_2',]
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    
    return xml_df

for i in ["test", "train"]:
    examples = xml_to_csv2("workspace/mobile/images/multi_lines/{}".format(i))
    #print(examples)

    examples.to_csv("workspace/mobile/images/multi_lines/{}.csv".format(i), index=None)

In [27]:
def shuffler():
    for i in ["test", "train"]:
        df = pd.read_csv("workspace/mobile/images/multi_lines/{}.csv".format(i))
        ds = df.sample(frac=1)
        ds.to_csv("workspace/mobile/images/multi_lines/{}.csv".format(i), index=None)
        
#shuffler()